/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units/index'
import { Route as TaxonomyIndexRouteImport } from './routes/taxonomy/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as TaxonomySpeciesRouteImport } from './routes/taxonomy/species'
import { Route as TaxonomyGeneraRouteImport } from './routes/taxonomy/genera'
import { Route as OrganizationsCreateRouteImport } from './routes/organizations/create'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations/$organizationId'
import { Route as OrganizationsOrganizationIdIndexRouteImport } from './routes/organizations/$organizationId/index'
import { Route as OrganizationsOrganizationIdMembersRouteImport } from './routes/organizations/$organizationId/members'
import { Route as OrganizationsOrganizationIdFoundationsRouteImport } from './routes/organizations/$organizationId/foundations'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyIndexRoute = TaxonomyIndexRouteImport.update({
  id: '/taxonomy/',
  path: '/taxonomy/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomySpeciesRoute = TaxonomySpeciesRouteImport.update({
  id: '/taxonomy/species',
  path: '/taxonomy/species',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyGeneraRoute = TaxonomyGeneraRouteImport.update({
  id: '/taxonomy/genera',
  path: '/taxonomy/genera',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsCreateRoute = OrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdIndexRoute =
  OrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any)
const OrganizationsOrganizationIdMembersRoute =
  OrganizationsOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any)
const OrganizationsOrganizationIdFoundationsRoute =
  OrganizationsOrganizationIdFoundationsRouteImport.update({
    id: '/foundations',
    path: '/foundations',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/organizations/create': typeof OrganizationsCreateRoute
  '/taxonomy/genera': typeof TaxonomyGeneraRoute
  '/taxonomy/species': typeof TaxonomySpeciesRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/taxonomy/': typeof TaxonomyIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/organizations/$organizationId/foundations': typeof OrganizationsOrganizationIdFoundationsRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/organizations/create': typeof OrganizationsCreateRoute
  '/taxonomy/genera': typeof TaxonomyGeneraRoute
  '/taxonomy/species': typeof TaxonomySpeciesRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/taxonomy': typeof TaxonomyIndexRoute
  '/units': typeof UnitsIndexRoute
  '/organizations/$organizationId/foundations': typeof OrganizationsOrganizationIdFoundationsRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/organizations/create': typeof OrganizationsCreateRoute
  '/taxonomy/genera': typeof TaxonomyGeneraRoute
  '/taxonomy/species': typeof TaxonomySpeciesRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/taxonomy/': typeof TaxonomyIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/organizations/$organizationId/foundations': typeof OrganizationsOrganizationIdFoundationsRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/organizations/$organizationId'
    | '/organizations/create'
    | '/taxonomy/genera'
    | '/taxonomy/species'
    | '/organizations/'
    | '/taxonomy/'
    | '/units/'
    | '/organizations/$organizationId/foundations'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/organizations/create'
    | '/taxonomy/genera'
    | '/taxonomy/species'
    | '/organizations'
    | '/taxonomy'
    | '/units'
    | '/organizations/$organizationId/foundations'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/organizations/$organizationId'
    | '/organizations/create'
    | '/taxonomy/genera'
    | '/taxonomy/species'
    | '/organizations/'
    | '/taxonomy/'
    | '/units/'
    | '/organizations/$organizationId/foundations'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRouteWithChildren
  OrganizationsCreateRoute: typeof OrganizationsCreateRoute
  TaxonomyGeneraRoute: typeof TaxonomyGeneraRoute
  TaxonomySpeciesRoute: typeof TaxonomySpeciesRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  TaxonomyIndexRoute: typeof TaxonomyIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy/': {
      id: '/taxonomy/'
      path: '/taxonomy'
      fullPath: '/taxonomy/'
      preLoaderRoute: typeof TaxonomyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy/species': {
      id: '/taxonomy/species'
      path: '/taxonomy/species'
      fullPath: '/taxonomy/species'
      preLoaderRoute: typeof TaxonomySpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy/genera': {
      id: '/taxonomy/genera'
      path: '/taxonomy/genera'
      fullPath: '/taxonomy/genera'
      preLoaderRoute: typeof TaxonomyGeneraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/create': {
      id: '/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof OrganizationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/': {
      id: '/organizations/$organizationId/'
      path: '/'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof OrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRoute
    }
    '/organizations/$organizationId/members': {
      id: '/organizations/$organizationId/members'
      path: '/members'
      fullPath: '/organizations/$organizationId/members'
      preLoaderRoute: typeof OrganizationsOrganizationIdMembersRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRoute
    }
    '/organizations/$organizationId/foundations': {
      id: '/organizations/$organizationId/foundations'
      path: '/foundations'
      fullPath: '/organizations/$organizationId/foundations'
      preLoaderRoute: typeof OrganizationsOrganizationIdFoundationsRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRoute
    }
  }
}

interface OrganizationsOrganizationIdRouteChildren {
  OrganizationsOrganizationIdFoundationsRoute: typeof OrganizationsOrganizationIdFoundationsRoute
  OrganizationsOrganizationIdMembersRoute: typeof OrganizationsOrganizationIdMembersRoute
  OrganizationsOrganizationIdIndexRoute: typeof OrganizationsOrganizationIdIndexRoute
}

const OrganizationsOrganizationIdRouteChildren: OrganizationsOrganizationIdRouteChildren =
  {
    OrganizationsOrganizationIdFoundationsRoute:
      OrganizationsOrganizationIdFoundationsRoute,
    OrganizationsOrganizationIdMembersRoute:
      OrganizationsOrganizationIdMembersRoute,
    OrganizationsOrganizationIdIndexRoute:
      OrganizationsOrganizationIdIndexRoute,
  }

const OrganizationsOrganizationIdRouteWithChildren =
  OrganizationsOrganizationIdRoute._addFileChildren(
    OrganizationsOrganizationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  OrganizationsOrganizationIdRoute:
    OrganizationsOrganizationIdRouteWithChildren,
  OrganizationsCreateRoute: OrganizationsCreateRoute,
  TaxonomyGeneraRoute: TaxonomyGeneraRoute,
  TaxonomySpeciesRoute: TaxonomySpeciesRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  TaxonomyIndexRoute: TaxonomyIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
