/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated._admin.index'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated._admin.units'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated._admin.taxonomy'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated._admin.organizations'
import { Route as AuthenticatedAdminOrganizationsOrganizationIdUsersRouteImport } from './routes/_authenticated._admin.organizations.$organizationId.users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/taxonomy',
    path: '/taxonomy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsOrganizationIdUsersRoute =
  AuthenticatedAdminOrganizationsOrganizationIdUsersRouteImport.update({
    id: '/$organizationId/users',
    path: '/$organizationId/users',
    getParentRoute: () => AuthenticatedAdminOrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRoute
  '/organizations': typeof AuthenticatedAdminOrganizationsRouteWithChildren
  '/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/units': typeof AuthenticatedAdminUnitsRoute
  '/organizations/$organizationId/users': typeof AuthenticatedAdminOrganizationsOrganizationIdUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRoute
  '/organizations': typeof AuthenticatedAdminOrganizationsRouteWithChildren
  '/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/units': typeof AuthenticatedAdminUnitsRoute
  '/organizations/$organizationId/users': typeof AuthenticatedAdminOrganizationsOrganizationIdUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_admin/organizations': typeof AuthenticatedAdminOrganizationsRouteWithChildren
  '/_authenticated/_admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/_admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/_admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/_admin/organizations/$organizationId/users': typeof AuthenticatedAdminOrganizationsOrganizationIdUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/organizations'
    | '/taxonomy'
    | '/units'
    | '/organizations/$organizationId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/organizations'
    | '/taxonomy'
    | '/units'
    | '/organizations/$organizationId/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/_admin/organizations'
    | '/_authenticated/_admin/taxonomy'
    | '/_authenticated/_admin/units'
    | '/_authenticated/_admin/'
    | '/_authenticated/_admin/organizations/$organizationId/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/': {
      id: '/_authenticated/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/units': {
      id: '/_authenticated/_admin/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/taxonomy': {
      id: '/_authenticated/_admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/organizations': {
      id: '/_authenticated/_admin/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/organizations/$organizationId/users': {
      id: '/_authenticated/_admin/organizations/$organizationId/users'
      path: '/$organizationId/users'
      fullPath: '/organizations/$organizationId/users'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsOrganizationIdUsersRouteImport
      parentRoute: typeof AuthenticatedAdminOrganizationsRoute
    }
  }
}

interface AuthenticatedAdminOrganizationsRouteChildren {
  AuthenticatedAdminOrganizationsOrganizationIdUsersRoute: typeof AuthenticatedAdminOrganizationsOrganizationIdUsersRoute
}

const AuthenticatedAdminOrganizationsRouteChildren: AuthenticatedAdminOrganizationsRouteChildren =
  {
    AuthenticatedAdminOrganizationsOrganizationIdUsersRoute:
      AuthenticatedAdminOrganizationsOrganizationIdUsersRoute,
  }

const AuthenticatedAdminOrganizationsRouteWithChildren =
  AuthenticatedAdminOrganizationsRoute._addFileChildren(
    AuthenticatedAdminOrganizationsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRouteWithChildren
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOrganizationsRoute:
    AuthenticatedAdminOrganizationsRouteWithChildren,
  AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
  AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
