/**
 * Every synced table, as a collection factory.
 *
 * Calling one is what a client does to obtain a collection; nothing is created by
 * importing this. Which tables an app actually creates, how each syncs, and
 * whether each accepts writes are the app's decisions — this package holds no
 * opinion about any of them, and none of them are recorded here.
 *
 * Field names are the Postgres column names, unchanged. Electric already streams
 * snake_case (the server forces the column list upstream), so leaving it alone
 * means no `columnMapper`, and the predicates a live query pushes down as subset
 * requests compile to SQL that needs no identifier rewriting.
 *
 * Four modules from `functions/` are exported alongside them, because a caller
 * cannot use a factory without them: the options each one takes, the wrapper that
 * names a write's command, the refusal a rejected write throws, and the route
 * derivation the server registers against. The rest of `functions/` is how the
 * factories are built and is nobody else's business.
 *
 * Generated by `pnpm generate:schemas`. Biome sorts the exports below, so the
 * four are somewhere in the middle of the list rather than at the top.
 */

export * from './additional_personnel.js';
export * from './addresses.js';
export * from './application_batches.js';
export * from './application_methods.js';
export * from './applications.js';
export * from './assignment_items.js';
export * from './assignments.js';
export * from './biocontrol_actions.js';
export * from './biocontrol_methods.js';
export * from './collection_lures.js';
export * from './collection_methods.js';
export * from './collection_species.js';
export * from './collections.js';
export * from './comments.js';
export * from './contacts.js';
export * from './equipment.js';
export * from './formulation_insecticides.js';
export * from './formulations.js';
export * from './functions/mutate-collection.js';
export * from './functions/routes.js';
export * from './functions/sync-collection.js';
export * from './functions/write-command.js';
export * from './genera.js';
export * from './habitat_types.js';
export * from './habitats.js';
export * from './insecticide_batches.js';
export * from './insecticides.js';
export * from './inspections.js';
export * from './memberships.js';
export * from './mission_items.js';
export * from './mission_notifications.js';
export * from './missions.js';
export * from './notification_registration_types.js';
export * from './notification_registrations.js';
export * from './notification_types.js';
export * from './organization_species.js';
export * from './organizations.js';
export * from './outreach_actions.js';
export * from './outreach_methods.js';
export * from './profiles.js';
export * from './region_folders.js';
export * from './regions.js';
export * from './requested_control_actions.js';
export * from './route_items.js';
export * from './routes.js';
export * from './sample_species.js';
export * from './samples.js';
export * from './service_requests.js';
export * from './source_reduction_methods.js';
export * from './source_reductions.js';
export * from './species.js';
export * from './tables/index.js';
export * from './tag_items.js';
export * from './tags.js';
export * from './traps.js';
export * from './units.js';
export * from './users.js';
export * from './vehicles.js';
export * from './weather_source_subscriptions.js';
export * from './weather_sources.js';
export * from './weather_summaries.js';
