/**
 * Every table in the database, as Kysely sees it.
 *
 * Generated by `pnpm generate:table-types` from `packages/db/schema.sql`, the
 * schema dbmate dumps when it applies the migrations. Do not edit it by hand:
 * `pnpm check:table-types` runs the generator and fails on any difference, so a
 * hand change is rejected by CI and overwritten by the next run.
 *
 * To change a type here, change the column. Write the migration, run
 * `pnpm db:migrate` so the dump moves with it, then `pnpm generate:table-types`.
 *
 * The row schemas in `packages/sync` are the client's half of the same columns,
 * and `packages/sync/src/tests/unit/collections/tables/drift.test.ts` holds them
 * to these interfaces at type level. It is generated too, by
 * `pnpm generate:schemas`.
 */

import type {
	AdultCollectionTimingMode,
	ControlType,
	InsecticideType,
	LarvalDensity,
	MembershipStatus,
	MissionNotificationStatus,
	NotificationChannel,
	OrganizationBillingMode,
	OrganizationSubscriptionStatus,
	RequestIntakeType,
	RouteType,
	SimmerRole,
	SpeciesSex,
	SpeciesStatus,
	UnitSystem,
	UnitType,
	WeatherSourceType,
} from '@simmer-mosquito/domain';
import type { ColumnType, Generated, RawBuilder } from 'kysely';

/**
 * Re-exported so a query and the domain command behind it name one type. The
 * members are not written here: `pnpm check:column-vocabularies` holds the
 * register's lists to this dump, ordered.
 */
export type {
	AdultCollectionTimingMode,
	ControlType,
	InsecticideType,
	LarvalDensity,
	MembershipStatus,
	MissionNotificationStatus,
	NotificationChannel,
	OrganizationBillingMode,
	OrganizationSubscriptionStatus,
	RequestIntakeType,
	RouteType,
	SimmerRole,
	SpeciesSex,
	SpeciesStatus,
	UnitSystem,
	UnitType,
	WeatherSourceType,
};

type TimestampWithDefault = ColumnType<Date, Date | undefined, Date | undefined>;
type NullableTimestampWithDefault = ColumnType<
	Date | null,
	Date | null | undefined,
	Date | null | undefined
>;
type BooleanWithDefault = ColumnType<boolean, boolean | undefined, boolean>;
type JsonColumn = ColumnType<unknown | null, unknown | null | undefined, unknown | null>;
/** A column the database fills and no write may set: a stored generated column, or one a trigger owns. */
type GeneratedColumn<T> = ColumnType<T, never, never>;
/**
 * A SQL `date`, which is a calendar day and not an instant.
 *
 * It reaches a collection as the `YYYY-MM-DD` string Electric streams and
 * reaches Kysely as whatever the pg driver parses, so the two transports
 * genuinely differ and the drift check compares the column and not its type.
 */
type DateColumn = ColumnType<Date, Date, Date>;
type NullableDateColumn = ColumnType<Date | null, Date | null | undefined, Date | null | undefined>;
/** PostGIS geometry. A write sends WKT or a `RawBuilder` around an `ST_` call. */
type GeometryColumn = ColumnType<
	string,
	string | RawBuilder<string> | undefined,
	string | RawBuilder<string> | undefined
>;

/** A GeoJSON geometry object, as `ST_AsGeoJSON` renders one. */
export type GeoJsonGeometry = Record<string, unknown>;

export interface AdditionalPersonnelTable {
	id: Generated<string>;
	organization_id: string;
	personnel_profile_id: string;
	entity_type: string;
	entity_id: string;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface AddressesTable {
	id: Generated<string>;
	organization_id: string;
	display_name: string;
	country: string;
	address_line_1: string | null;
	address_line_2: string | null;
	locality: string | null;
	region: string | null;
	postal_code: string | null;
	geocoder_response: JsonColumn;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface ApplicationBatchesTable {
	id: Generated<string>;
	application_id: string;
	insecticide_batch_id: string;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface ApplicationMethodsTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	custom_schema: JsonColumn;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface ApplicationsTable {
	id: Generated<string>;
	organization_id: string;
	application_method_id: string | null;
	insecticide_id: string;
	applicator_profile_id: string | null;
	application_date: DateColumn;
	address_id: string | null;
	vehicle_id: string | null;
	equipment_id: string | null;
	amount_applied: number;
	application_unit_id: string;
	habitat_id: string | null;
	collection_id: string | null;
	inspection_id: string | null;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	requested_control_action_id: string | null;
	mission_item_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface AssignmentItemsTable {
	id: Generated<string>;
	assignment_id: string;
	entity_type: string;
	entity_id: string;
	position: number;
	directions_to_next_item: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	completed_at: NullableTimestampWithDefault;
	completed_by_profile_id: string | null;
	skipped_at: NullableTimestampWithDefault;
	skipped_by_profile_id: string | null;
	skip_reason: string | null;
	organization_id: string;
}

export interface AssignmentsTable {
	id: Generated<string>;
	organization_id: string;
	assignment_name: string | null;
	assigned_to_profile_id: string | null;
	assigned_by_profile_id: string | null;
	assignment_date: DateColumn;
	due_at: NullableTimestampWithDefault;
	started_at: NullableTimestampWithDefault;
	completed_at: NullableTimestampWithDefault;
	cancelled_at: NullableTimestampWithDefault;
	cancellation_reason: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface BiocontrolActionsTable {
	id: Generated<string>;
	organization_id: string;
	biocontrol_method_id: string;
	technician_profile_id: string | null;
	biocontrol_date: DateColumn;
	address_id: string | null;
	habitat_id: string | null;
	inspection_id: string | null;
	amount_released: number;
	release_unit_id: string;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	requested_control_action_id: string | null;
	mission_item_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface BiocontrolMethodsTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	custom_schema: JsonColumn;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface CollectionLuresTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	description: string | null;
	is_active: BooleanWithDefault;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
}

export interface CollectionMethodsTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	description: string | null;
	custom_schema: JsonColumn;
	is_active: BooleanWithDefault;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	action_threshold: number | null;
}

export interface CollectionSpeciesTable {
	id: Generated<string>;
	collection_id: string;
	species_id: string;
	count: number;
	sex: SpeciesSex | null;
	status: SpeciesStatus | null;
	identified_by_profile_id: string | null;
	identified_date: DateColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface CollectionsTable {
	id: Generated<string>;
	organization_id: string;
	trap_id: string | null;
	collection_method_id: string;
	collection_lure_id: string | null;
	address_id: string | null;
	collected_at: NullableTimestampWithDefault;
	collected_by_profile_id: string | null;
	started_at: NullableTimestampWithDefault;
	set_by_profile_id: string | null;
	has_problem: BooleanWithDefault;
	is_zero_result: BooleanWithDefault;
	has_bycatch: BooleanWithDefault;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	collection_timing_mode: Generated<AdultCollectionTimingMode>;
	collection_date: NullableDateColumn;
	duration_amount: number | null;
	duration_unit_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
	set_assignment_item_id: string | null;
	collected_assignment_item_id: string | null;
}

export interface CommentsTable {
	id: Generated<string>;
	organization_id: string;
	entity_type: string;
	entity_id: string;
	comment_text: string;
	commented_by_profile_id: string | null;
	commented_at: TimestampWithDefault;
	is_pinned: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface ContactsTable {
	id: Generated<string>;
	organization_id: string;
	contact_name: string | null;
	preferred_phone: string | null;
	alternate_phone: string | null;
	email: string | null;
	company: string | null;
	department: string | null;
	title: string | null;
	wants_email: BooleanWithDefault;
	wants_sms: BooleanWithDefault;
	wants_phone: BooleanWithDefault;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface EquipmentTable {
	id: Generated<string>;
	organization_id: string;
	equipment_name: string;
	serial_number: string | null;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	is_active: BooleanWithDefault;
}

export interface FormulationInsecticidesTable {
	id: Generated<string>;
	formulation_id: string;
	insecticide_id: string;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
	amount: number;
	unit_id: string;
}

export interface FormulationsTable {
	id: Generated<string>;
	organization_id: string;
	formulation_name: string;
	description: string | null;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	batch_size: number;
	batch_unit_id: string;
}

export interface GeneraTable {
	id: Generated<string>;
	abbreviation: string;
	name: string;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
}

export interface HabitatTypesTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	description: string | null;
	custom_schema: JsonColumn;
	is_active: BooleanWithDefault;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
}

export interface HabitatsTable {
	id: Generated<string>;
	organization_id: string;
	address_id: string | null;
	habitat_type_id: string | null;
	habitat_name: string | null;
	description: string;
	is_active: BooleanWithDefault;
	is_inaccessible: BooleanWithDefault;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface InsecticideBatchesTable {
	id: Generated<string>;
	insecticide_id: string;
	batch_name: string;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface InsecticidesTable {
	id: Generated<string>;
	organization_id: string;
	trade_name: string;
	active_ingredient: string;
	is_active: BooleanWithDefault;
	type: InsecticideType;
	registration_number: string;
	default_unit_id: string;
	inventory_unit_id: string | null;
	conversion_factor: number | null;
	label_url: string | null;
	msds_url: string | null;
	shorthand: string | null;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface InspectionsTable {
	id: Generated<string>;
	organization_id: string;
	habitat_id: string | null;
	habitat_type_id: string | null;
	address_id: string | null;
	inspected_by_profile_id: string | null;
	inspection_date: DateColumn;
	is_wet: BooleanWithDefault;
	dip_count: number | null;
	density: LarvalDensity | null;
	larvae_count: number | null;
	has_first_instar: BooleanWithDefault;
	has_second_instar: BooleanWithDefault;
	has_third_instar: BooleanWithDefault;
	has_fourth_instar: BooleanWithDefault;
	has_pupae: BooleanWithDefault;
	has_eggs: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
	assignment_item_id: string | null;
}

export interface MembershipsTable {
	id: Generated<string>;
	organization_id: string;
	user_id: string | null;
	profile_id: string;
	role: SimmerRole;
	status: Generated<MembershipStatus>;
	is_default: BooleanWithDefault;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	invited_email: string | null;
	workos_invitation_id: string | null;
}

export interface MissionItemsTable {
	id: Generated<string>;
	mission_id: string;
	requested_control_action_id: string | null;
	address_id: string | null;
	position: number;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	completed_at: NullableTimestampWithDefault;
	completed_by_profile_id: string | null;
	skipped_at: NullableTimestampWithDefault;
	skipped_by_profile_id: string | null;
	skip_reason: string | null;
	organization_id: string;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface MissionNotificationsTable {
	id: Generated<string>;
	mission_id: string;
	notification_registration_id: string;
	contact_id: string;
	notification_type_id: string;
	channel: NotificationChannel;
	destination: string | null;
	status: Generated<MissionNotificationStatus>;
	status_changed_at: NullableTimestampWithDefault;
	status_changed_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface MissionsTable {
	id: Generated<string>;
	organization_id: string;
	mission_name: string | null;
	control_type: ControlType;
	planned_method_id: string | null;
	assigned_to_profile_id: string | null;
	assigned_by_profile_id: string | null;
	scheduled_start_at: Date;
	scheduled_end_at: NullableTimestampWithDefault;
	rain_date: NullableDateColumn;
	started_at: NullableTimestampWithDefault;
	completed_at: NullableTimestampWithDefault;
	cancelled_at: NullableTimestampWithDefault;
	cancellation_reason: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	notification_type_id: string | null;
}

export interface NotificationRegistrationTypesTable {
	id: Generated<string>;
	notification_registration_id: string;
	notification_type_id: string;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface NotificationRegistrationsTable {
	id: Generated<string>;
	contact_id: string;
	address_id: string | null;
	buffer_distance: number | null;
	buffer_unit_id: string | null;
	has_bees: BooleanWithDefault;
	is_no_spray: BooleanWithDefault;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface NotificationTypesTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	description: string | null;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface OrganizationSpeciesTable {
	id: Generated<string>;
	organization_id: string;
	species_id: string;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface OrganizationsTable {
	id: Generated<string>;
	workos_organization_id: string | null;
	name: string;
	slug: string | null;
	settings: JsonColumn;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	subscription_status: Generated<OrganizationSubscriptionStatus>;
	billing_mode: Generated<OrganizationBillingMode>;
	billing_contact_name: string | null;
	billing_contact_email: string | null;
	subscription_notes: string | null;
	main_contact_email: string | null;
	phone_number: string | null;
	mailing_country: string | null;
	mailing_address_line_1: string | null;
	mailing_address_line_2: string | null;
	mailing_locality: string | null;
	mailing_region: string | null;
	mailing_postal_code: string | null;
	updated_by_profile_id: string | null;
}

export interface OutreachActionsTable {
	id: Generated<string>;
	organization_id: string;
	outreach_method_id: string;
	technician_profile_id: string | null;
	outreach_date: DateColumn;
	address_id: string | null;
	inspection_id: string | null;
	reach: number;
	reach_description: string | null;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	requested_control_action_id: string | null;
	mission_item_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface OutreachMethodsTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	custom_schema: JsonColumn;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface ProfilesTable {
	id: Generated<string>;
	organization_id: string;
	user_id: string | null;
	display_name: string;
	email: string | null;
	is_active: BooleanWithDefault;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface RegionFoldersTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	description: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
}

export interface RegionsTable {
	id: Generated<string>;
	organization_id: string;
	region_folder_id: string | null;
	name: string;
	description: string | null;
	metadata: JsonColumn;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geom_type: GeneratedColumn<string>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
}

export interface RequestedControlActionsTable {
	id: Generated<string>;
	organization_id: string;
	control_type: ControlType;
	recommended_method_id: string | null;
	summary: string | null;
	inspection_id: string | null;
	collection_id: string | null;
	address_id: string | null;
	requested_by_profile_id: string | null;
	requested_at: TimestampWithDefault;
	resolved_at: NullableTimestampWithDefault;
	resolved_by_profile_id: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	habitat_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface RouteItemsTable {
	id: Generated<string>;
	route_id: string;
	entity_type: string;
	entity_id: string;
	position: number;
	directions_to_next_item: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface RoutesTable {
	id: Generated<string>;
	organization_id: string;
	route_name: string;
	route_type: Generated<RouteType>;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface SampleSpeciesTable {
	id: Generated<string>;
	sample_id: string;
	species_id: string;
	identified_by_profile_id: string | null;
	identified_at: DateColumn;
	larvae_count: number;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface SamplesTable {
	id: Generated<string>;
	inspection_id: string;
	display_name: string | null;
	is_zero_larvae: BooleanWithDefault;
	has_non_mosquito: BooleanWithDefault;
	unidentifiable_reason: string | null;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface ServiceRequestsTable {
	id: Generated<string>;
	organization_id: string;
	display_name: number | null;
	intake_type: Generated<RequestIntakeType>;
	request_date: DateColumn;
	address_id: string;
	contact_id: string;
	received_by_profile_id: string | null;
	details: string;
	closed_at: NullableTimestampWithDefault;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	closed_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface SourceReductionMethodsTable {
	id: Generated<string>;
	organization_id: string;
	name: string;
	custom_schema: JsonColumn;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface SourceReductionsTable {
	id: Generated<string>;
	organization_id: string;
	source_reduction_method_id: string;
	technician_profile_id: string | null;
	source_reduction_date: DateColumn;
	address_id: string | null;
	sources_eliminated_amount: number;
	sources_eliminated_unit_id: string;
	inspection_id: string | null;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	requested_control_action_id: string | null;
	habitat_id: string | null;
	mission_item_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface SpeciesTable {
	id: Generated<string>;
	genus_id: string | null;
	epithet: string;
	common_name: string | null;
	display_name: string;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
}

export interface TagItemsTable {
	id: Generated<string>;
	tag_id: string;
	entity_type: string;
	entity_id: string;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	organization_id: string;
}

export interface TagsTable {
	id: Generated<string>;
	organization_id: string;
	tag_name: string;
	description: string | null;
	color: string | null;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface TrapsTable {
	id: Generated<string>;
	organization_id: string;
	collection_method_id: string;
	address_id: string | null;
	collection_lure_id: string | null;
	trap_name: string | null;
	trap_code: string | null;
	description: string | null;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
}

export interface UnitsTable {
	id: Generated<string>;
	unit_name: string;
	abbreviation: string;
	unit_type: UnitType;
	unit_system: UnitSystem;
	created_at: TimestampWithDefault;
	code: string;
}

export interface UsersTable {
	id: Generated<string>;
	workos_user_id: string;
	email: string;
	display_name: string;
	first_name: string | null;
	last_name: string | null;
	email_verified: boolean | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
}

export interface VehiclesTable {
	id: Generated<string>;
	organization_id: string;
	vehicle_name: string;
	metadata: JsonColumn;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	is_active: BooleanWithDefault;
}

export interface WeatherSourceSubscriptionsTable {
	id: Generated<string>;
	organization_id: string;
	weather_source_id: string;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
}

export interface WeatherSourcesTable {
	id: Generated<string>;
	organization_id: string | null;
	source_type: WeatherSourceType;
	source_name: string;
	source_code: string | null;
	provider_source_id: string | null;
	is_active: BooleanWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	deleted_at: NullableTimestampWithDefault;
	deleted_by_profile_id: string | null;
	geom: GeometryColumn;
	lat: GeneratedColumn<number>;
	lng: GeneratedColumn<number>;
	geojson: GeneratedColumn<GeoJsonGeometry>;
	geom_type: GeneratedColumn<string>;
	metadata: JsonColumn;
}

export interface WeatherSummariesTable {
	id: Generated<string>;
	weather_source_id: string;
	start_date: DateColumn;
	end_date: DateColumn;
	temperature_min_f: number | null;
	temperature_max_f: number | null;
	precipitation_inches: number | null;
	relative_humidity_min: number | null;
	relative_humidity_max: number | null;
	wind_speed_min_mph: number | null;
	wind_speed_max_mph: number | null;
	created_at: TimestampWithDefault;
	updated_at: TimestampWithDefault;
	created_by_profile_id: string | null;
	updated_by_profile_id: string | null;
	organization_id: string | null;
}

/** The database Kysely is parameterised by. Every table, keyed by its SQL name. */
export interface SimmerDatabase {
	additional_personnel: AdditionalPersonnelTable;
	addresses: AddressesTable;
	application_batches: ApplicationBatchesTable;
	application_methods: ApplicationMethodsTable;
	applications: ApplicationsTable;
	assignment_items: AssignmentItemsTable;
	assignments: AssignmentsTable;
	biocontrol_actions: BiocontrolActionsTable;
	biocontrol_methods: BiocontrolMethodsTable;
	collection_lures: CollectionLuresTable;
	collection_methods: CollectionMethodsTable;
	collection_species: CollectionSpeciesTable;
	collections: CollectionsTable;
	comments: CommentsTable;
	contacts: ContactsTable;
	equipment: EquipmentTable;
	formulation_insecticides: FormulationInsecticidesTable;
	formulations: FormulationsTable;
	genera: GeneraTable;
	habitat_types: HabitatTypesTable;
	habitats: HabitatsTable;
	insecticide_batches: InsecticideBatchesTable;
	insecticides: InsecticidesTable;
	inspections: InspectionsTable;
	memberships: MembershipsTable;
	mission_items: MissionItemsTable;
	mission_notifications: MissionNotificationsTable;
	missions: MissionsTable;
	notification_registration_types: NotificationRegistrationTypesTable;
	notification_registrations: NotificationRegistrationsTable;
	notification_types: NotificationTypesTable;
	organization_species: OrganizationSpeciesTable;
	organizations: OrganizationsTable;
	outreach_actions: OutreachActionsTable;
	outreach_methods: OutreachMethodsTable;
	profiles: ProfilesTable;
	region_folders: RegionFoldersTable;
	regions: RegionsTable;
	requested_control_actions: RequestedControlActionsTable;
	route_items: RouteItemsTable;
	routes: RoutesTable;
	sample_species: SampleSpeciesTable;
	samples: SamplesTable;
	service_requests: ServiceRequestsTable;
	source_reduction_methods: SourceReductionMethodsTable;
	source_reductions: SourceReductionsTable;
	species: SpeciesTable;
	tag_items: TagItemsTable;
	tags: TagsTable;
	traps: TrapsTable;
	units: UnitsTable;
	users: UsersTable;
	vehicles: VehiclesTable;
	weather_source_subscriptions: WeatherSourceSubscriptionsTable;
	weather_sources: WeatherSourcesTable;
	weather_summaries: WeatherSummariesTable;
}
