-- habitat tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select h.id, h.habitat_name as "habitatName", h.habitat_type_id as "habitatTypeId", h.is_active as "isActive", h.is_inaccessible as "isInaccessible", h.geom_type as "geomType", st_asmvtgeom( st_transform(h.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from habitats h cross join bounds where h.organization_id = $9 and h.deleted_at is null and h.is_active = $10 and h.is_inaccessible = $11 and h.habitat_type_id = any($12::uuid[]) and exists ( select 1 from tag_items ti where ti.entity_type = 'habitat' and ti.entity_id = h.id and ti.deleted_at is null and ti.tag_id = any($13::uuid[]) ) and exists ( select 1 from regions rf where rf.id = any($14::uuid[]) and rf.organization_id = h.organization_id and rf.deleted_at is null and rf.geom && h.geom and st_intersects(rf.geom, h.geom) ) and ( position(lower($15) in lower(coalesce(h.habitat_name, ''))) > 0 or position(lower($16) in lower(h.description)) > 0 ) and h.geom && bounds.geom_4326 and st_intersects(h.geom, bounds.geom_4326) ) select coalesce(st_asmvt(tile_rows, $17::text, $18, 'geom'), ''::bytea) as tile from tile_rows

-- habitat bbox list
with bounds as ( select st_makeenvelope( $1, $2, $3, $4, 4326 ) as geom_4326 ) select h.id, h.organization_id as "organizationId", h.lat, h.lng, h.geojson, h.geom_type as "geomType", h.address_id as "addressId", h.habitat_type_id as "habitatTypeId", h.habitat_name as "habitatName", h.description, h.is_active as "isActive", h.is_inaccessible as "isInaccessible", h.metadata, h.created_by_profile_id as "createdByProfileId", h.updated_by_profile_id as "updatedByProfileId", h.created_at as "createdAt", h.updated_at as "updatedAt", count(*) over()::int as "total" from habitats h cross join bounds where h.organization_id = $5 and h.deleted_at is null and h.is_active = $6 and h.habitat_type_id = any($7::uuid[]) and exists ( select 1 from tag_items ti where ti.entity_type = 'habitat' and ti.entity_id = h.id and ti.deleted_at is null and ti.tag_id = any($8::uuid[]) ) and exists ( select 1 from regions rf where rf.id = any($9::uuid[]) and rf.organization_id = h.organization_id and rf.deleted_at is null and rf.geom && h.geom and st_intersects(rf.geom, h.geom) ) and ( position(lower($10) in lower(coalesce(h.habitat_name, ''))) > 0 or position(lower($11) in lower(h.description)) > 0 ) and h.geom && bounds.geom_4326 and st_intersects(h.geom, bounds.geom_4326) order by coalesce(h.habitat_name, h.id::text), h.id limit $12 offset $13

-- habitat extent
with extent as ( select st_extent(h.geom) as box from habitats h where h.organization_id = $1 and h.deleted_at is null and h.is_active = $2 and h.habitat_type_id = any($3::uuid[]) and exists ( select 1 from tag_items ti where ti.entity_type = 'habitat' and ti.entity_id = h.id and ti.deleted_at is null and ti.tag_id = any($4::uuid[]) ) and exists ( select 1 from regions rf where rf.id = any($5::uuid[]) and rf.organization_id = h.organization_id and rf.deleted_at is null and rf.geom && h.geom and st_intersects(rf.geom, h.geom) ) and ( position(lower($6) in lower(coalesce(h.habitat_name, ''))) > 0 or position(lower($7) in lower(h.description)) > 0 ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- habitat by id
select h.id, h.organization_id as "organizationId", h.lat, h.lng, h.geojson, h.geom_type as "geomType", h.address_id as "addressId", h.habitat_type_id as "habitatTypeId", h.habitat_name as "habitatName", h.description, h.is_active as "isActive", h.is_inaccessible as "isInaccessible", h.metadata, h.created_by_profile_id as "createdByProfileId", h.updated_by_profile_id as "updatedByProfileId", h.created_at as "createdAt", h.updated_at as "updatedAt" from habitats h where h.id = $1 and h.organization_id = $2 and h.deleted_at is null limit 1

-- inspection tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select i.id, i.is_wet as "isWet", i.density::text as "density", i.habitat_type_id as "habitatTypeId", ( i.has_eggs or i.has_first_instar or i.has_second_instar or i.has_third_instar or i.has_fourth_instar or i.has_pupae ) as "positive", st_asmvtgeom( st_transform(i.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from inspections i cross join bounds where i.organization_id = $9 and i.deleted_at is null and i.is_wet = $10 and i.density = any($11::larval_density[]) and ( i.has_eggs or i.has_first_instar or i.has_second_instar or i.has_third_instar or i.has_fourth_instar or i.has_pupae ) and i.habitat_type_id = any($12::uuid[]) and i.inspected_by_profile_id = any($13::uuid[]) and i.inspection_date >= $14 and i.inspection_date <= $15 and exists ( select 1 from regions rf where rf.id = any($16::uuid[]) and rf.organization_id = i.organization_id and rf.deleted_at is null and rf.geom && i.geom and st_intersects(rf.geom, i.geom) ) and i.geom && bounds.geom_4326 and st_intersects(i.geom, bounds.geom_4326) ) select coalesce(st_asmvt(tile_rows, $17::text, $18, 'geom'), ''::bytea) as tile from tile_rows

-- inspection bbox list
with bounds as ( select st_makeenvelope( $1, $2, $3, $4, 4326 ) as geom_4326 ) select i.id, i.organization_id as "organizationId", i.lat, i.lng, i.geojson, i.geom_type as "geomType", i.habitat_id as "habitatId", h.habitat_name as "habitatName", i.habitat_type_id as "habitatTypeId", i.address_id as "addressId", a.display_name as "addressDisplayName", i.inspected_by_profile_id as "inspectedByProfileId", p.display_name as "inspectedByName", i.inspection_date::text as "inspectionDate", i.is_wet as "isWet", i.dip_count as "dipCount", i.density::text as "density", i.larvae_count as "larvaeCount", i.has_eggs as "hasEggs", i.has_first_instar as "hasFirstInstar", i.has_second_instar as "hasSecondInstar", i.has_third_instar as "hasThirdInstar", i.has_fourth_instar as "hasFourthInstar", i.has_pupae as "hasPupae", i.created_at as "createdAt", i.updated_at as "updatedAt" , count(*) over()::int as "total" from inspections i left join habitats h on h.id = i.habitat_id left join addresses a on a.id = i.address_id left join profiles p on p.id = i.inspected_by_profile_id cross join bounds where i.organization_id = $5 and i.deleted_at is null and i.is_wet = $6 and i.density = any($7::larval_density[]) and ( i.has_eggs or i.has_first_instar or i.has_second_instar or i.has_third_instar or i.has_fourth_instar or i.has_pupae ) and i.habitat_type_id = any($8::uuid[]) and i.inspected_by_profile_id = any($9::uuid[]) and i.inspection_date >= $10 and i.inspection_date <= $11 and exists ( select 1 from regions rf where rf.id = any($12::uuid[]) and rf.organization_id = i.organization_id and rf.deleted_at is null and rf.geom && i.geom and st_intersects(rf.geom, i.geom) ) and i.geom && bounds.geom_4326 and st_intersects(i.geom, bounds.geom_4326) order by i.inspection_date desc, i.created_at desc, i.id limit $13 offset $14

-- inspection extent
with extent as ( select st_extent(i.geom) as box from inspections i where i.organization_id = $1 and i.deleted_at is null and i.is_wet = $2 and i.density = any($3::larval_density[]) and ( i.has_eggs or i.has_first_instar or i.has_second_instar or i.has_third_instar or i.has_fourth_instar or i.has_pupae ) and i.habitat_type_id = any($4::uuid[]) and i.inspected_by_profile_id = any($5::uuid[]) and i.inspection_date >= $6 and i.inspection_date <= $7 and exists ( select 1 from regions rf where rf.id = any($8::uuid[]) and rf.organization_id = i.organization_id and rf.deleted_at is null and rf.geom && i.geom and st_intersects(rf.geom, i.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- inspection by id
select i.id, i.organization_id as "organizationId", i.lat, i.lng, i.geojson, i.geom_type as "geomType", i.habitat_id as "habitatId", h.habitat_name as "habitatName", i.habitat_type_id as "habitatTypeId", i.address_id as "addressId", a.display_name as "addressDisplayName", i.inspected_by_profile_id as "inspectedByProfileId", p.display_name as "inspectedByName", i.inspection_date::text as "inspectionDate", i.is_wet as "isWet", i.dip_count as "dipCount", i.density::text as "density", i.larvae_count as "larvaeCount", i.has_eggs as "hasEggs", i.has_first_instar as "hasFirstInstar", i.has_second_instar as "hasSecondInstar", i.has_third_instar as "hasThirdInstar", i.has_fourth_instar as "hasFourthInstar", i.has_pupae as "hasPupae", i.created_at as "createdAt", i.updated_at as "updatedAt" from inspections i left join habitats h on h.id = i.habitat_id left join addresses a on a.id = i.address_id left join profiles p on p.id = i.inspected_by_profile_id where i.id = $1 and i.organization_id = $2 and i.deleted_at is null limit 1

-- sample tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select s.id, ( case when exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) then 'identified' when s.is_zero_larvae then 'zero_larvae' when s.unidentifiable_reason is not null then 'unidentifiable' else 'awaiting' end ) as "status", st_asmvtgeom( st_transform(i.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from samples s join inspections i on i.id = s.inspection_id cross join bounds where s.organization_id = $9 and s.deleted_at is null and i.deleted_at is null and i.geom is not null and i.inspection_date >= $10 and i.inspection_date <= $11 and s.has_non_mosquito = true and exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null and ss.species_id = any($12::uuid[]) ) and exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) and exists ( select 1 from regions rf where rf.id = any($13::uuid[]) and rf.organization_id = s.organization_id and rf.deleted_at is null and rf.geom && i.geom and st_intersects(rf.geom, i.geom) ) and i.geom && bounds.geom_4326 and st_intersects(i.geom, bounds.geom_4326) ) select coalesce(st_asmvt(tile_rows, $14::text, $15, 'geom'), ''::bytea) as tile from tile_rows

-- sample bbox list
with bounds as ( select st_makeenvelope( $1, $2, $3, $4, 4326 ) as geom_4326 ) select s.id, s.organization_id as "organizationId", i.lat, i.lng, i.geojson, i.geom_type as "geomType", s.display_name as "displayName", s.inspection_id as "inspectionId", i.inspection_date::text as "inspectionDate", i.habitat_id as "habitatId", h.habitat_name as "habitatName", s.is_zero_larvae as "isZeroLarvae", s.has_non_mosquito as "hasNonMosquito", s.unidentifiable_reason as "unidentifiableReason", s.created_by_profile_id as "createdByProfileId", ( case when exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) then 'identified' when s.is_zero_larvae then 'zero_larvae' when s.unidentifiable_reason is not null then 'unidentifiable' else 'awaiting' end ) as "status", agg.identified_at as "identifiedAt", coalesce(agg.larvae_total, 0)::int as "larvaeTotal", coalesce(agg.results, '[]'::json) as "results", s.created_at as "createdAt", s.updated_at as "updatedAt" , count(*) over()::int as "total" from samples s join inspections i on i.id = s.inspection_id left join habitats h on h.id = i.habitat_id left join lateral ( select max(ss.identified_at)::text as identified_at, sum(ss.larvae_count)::int as larvae_total, json_agg( json_build_object('speciesId', ss.species_id, 'larvaeCount', ss.larvae_count) order by ss.larvae_count desc, ss.species_id ) as results from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) agg on true cross join bounds where s.organization_id = $5 and s.deleted_at is null and i.deleted_at is null and i.geom is not null and i.inspection_date >= $6 and i.inspection_date <= $7 and s.has_non_mosquito = true and exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null and ss.species_id = any($8::uuid[]) ) and ( s.is_zero_larvae = false and s.unidentifiable_reason is null and not exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) ) and exists ( select 1 from regions rf where rf.id = any($9::uuid[]) and rf.organization_id = s.organization_id and rf.deleted_at is null and rf.geom && i.geom and st_intersects(rf.geom, i.geom) ) and i.geom && bounds.geom_4326 and st_intersects(i.geom, bounds.geom_4326) order by i.inspection_date desc, s.created_at desc, s.id limit $10 offset $11

-- sample extent
with extent as ( select st_extent(i.geom) as box from samples s join inspections i on i.id = s.inspection_id where s.organization_id = $1 and s.deleted_at is null and i.deleted_at is null and i.geom is not null and i.inspection_date >= $2 and i.inspection_date <= $3 and s.has_non_mosquito = true and exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null and ss.species_id = any($4::uuid[]) ) and s.is_zero_larvae = true and exists ( select 1 from regions rf where rf.id = any($5::uuid[]) and rf.organization_id = s.organization_id and rf.deleted_at is null and rf.geom && i.geom and st_intersects(rf.geom, i.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- sample by id
select s.id, s.organization_id as "organizationId", i.lat, i.lng, i.geojson, i.geom_type as "geomType", s.display_name as "displayName", s.inspection_id as "inspectionId", i.inspection_date::text as "inspectionDate", i.habitat_id as "habitatId", h.habitat_name as "habitatName", s.is_zero_larvae as "isZeroLarvae", s.has_non_mosquito as "hasNonMosquito", s.unidentifiable_reason as "unidentifiableReason", s.created_by_profile_id as "createdByProfileId", ( case when exists ( select 1 from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) then 'identified' when s.is_zero_larvae then 'zero_larvae' when s.unidentifiable_reason is not null then 'unidentifiable' else 'awaiting' end ) as "status", agg.identified_at as "identifiedAt", coalesce(agg.larvae_total, 0)::int as "larvaeTotal", coalesce(agg.results, '[]'::json) as "results", s.created_at as "createdAt", s.updated_at as "updatedAt" from samples s join inspections i on i.id = s.inspection_id left join habitats h on h.id = i.habitat_id left join lateral ( select max(ss.identified_at)::text as identified_at, sum(ss.larvae_count)::int as larvae_total, json_agg( json_build_object('speciesId', ss.species_id, 'larvaeCount', ss.larvae_count) order by ss.larvae_count desc, ss.species_id ) as results from sample_species ss where ss.sample_id = s.id and ss.deleted_at is null ) agg on true where s.id = $1 and s.organization_id = $2 and s.deleted_at is null and i.deleted_at is null and i.geom is not null limit 1

-- trap tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select t.id, t.is_active as "isActive", st_asmvtgeom( st_transform(t.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from traps t cross join bounds where t.organization_id = $9 and t.deleted_at is null and t.geom && bounds.geom_4326 and st_intersects(t.geom, bounds.geom_4326) and t.collection_method_id = any($10::uuid[]) and t.is_active = $11 and ( t.trap_name ilike $12 or t.trap_code ilike $13 or t.description ilike $14 ) and exists ( select 1 from regions rf where rf.id = any($15::uuid[]) and rf.organization_id = t.organization_id and rf.deleted_at is null and rf.geom && t.geom and st_intersects(rf.geom, t.geom) ) ) select coalesce(st_asmvt(tile_rows, $16::text, $17, 'geom'), ''::bytea) as tile from tile_rows

-- trap page
select t.id, t.organization_id as "organizationId", t.lat, t.lng, t.geojson, t.geom_type as "geomType", t.collection_method_id as "collectionMethodId", t.collection_lure_id as "collectionLureId", t.address_id as "addressId", t.trap_name as "trapName", t.trap_code as "trapCode", t.description, t.is_active as "isActive", t.created_at as "createdAt", t.updated_at as "updatedAt" , count(*) over()::int as "total" from traps t where t.organization_id = $1 and t.deleted_at is null and t.collection_method_id = any($2::uuid[]) and t.is_active = $3 and ( t.trap_name ilike $4 or t.trap_code ilike $5 or t.description ilike $6 ) and exists ( select 1 from regions rf where rf.id = any($7::uuid[]) and rf.organization_id = t.organization_id and rf.deleted_at is null and rf.geom && t.geom and st_intersects(rf.geom, t.geom) ) -- Sort by what the client shows first ("code - name"), so the list reads in order. order by coalesce(t.trap_code, t.trap_name) asc nulls last, t.created_at desc, t.id limit $8 offset $9

-- trap extent
with extent as ( select st_extent(t.geom) as box from traps t where t.organization_id = $1 and t.deleted_at is null and t.collection_method_id = any($2::uuid[]) and t.is_active = $3 and ( t.trap_name ilike $4 or t.trap_code ilike $5 or t.description ilike $6 ) and exists ( select 1 from regions rf where rf.id = any($7::uuid[]) and rf.organization_id = t.organization_id and rf.deleted_at is null and rf.geom && t.geom and st_intersects(rf.geom, t.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- trap by id
select t.id, t.organization_id as "organizationId", t.lat, t.lng, t.geojson, t.geom_type as "geomType", t.collection_method_id as "collectionMethodId", t.collection_lure_id as "collectionLureId", t.address_id as "addressId", t.trap_name as "trapName", t.trap_code as "trapCode", t.description, t.is_active as "isActive", t.created_at as "createdAt", t.updated_at as "updatedAt" from traps t where t.id = $1 and t.organization_id = $2 and t.deleted_at is null limit 1

-- collection tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select c.id, c.has_problem as "hasProblem", st_asmvtgeom( st_transform(c.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from collections c cross join bounds where c.organization_id = $9 and c.deleted_at is null and c.geom && bounds.geom_4326 and st_intersects(c.geom, bounds.geom_4326) and c.collection_method_id = any($10::uuid[]) and c.has_problem = true and coalesce(c.collected_at::date, c.collection_date) >= $11 and coalesce(c.collected_at::date, c.collection_date) <= $12 and exists ( select 1 from regions rf where rf.id = any($13::uuid[]) and rf.organization_id = c.organization_id and rf.deleted_at is null and rf.geom && c.geom and st_intersects(rf.geom, c.geom) ) ) select coalesce(st_asmvt(tile_rows, $14::text, $15, 'geom'), ''::bytea) as tile from tile_rows

-- collection page
select c.id, c.organization_id as "organizationId", c.trap_id as "trapId", c.lat, c.lng, c.geojson, c.geom_type as "geomType", c.collection_method_id as "collectionMethodId", c.collected_at::text as "collectedAt", c.collection_date::text as "collectionDate", c.has_problem as "hasProblem", c.is_zero_result as "isZeroResult", c.has_bycatch as "hasBycatch", c.set_by_profile_id as "setByProfileId", c.collected_by_profile_id as "collectedByProfileId", c.created_at as "createdAt", c.updated_at as "updatedAt" , count(*) over()::int as "total" from collections c where c.organization_id = $1 and c.deleted_at is null and c.collection_method_id = any($2::uuid[]) and c.has_problem = true and coalesce(c.collected_at::date, c.collection_date) >= $3 and coalesce(c.collected_at::date, c.collection_date) <= $4 and exists ( select 1 from regions rf where rf.id = any($5::uuid[]) and rf.organization_id = c.organization_id and rf.deleted_at is null and rf.geom && c.geom and st_intersects(rf.geom, c.geom) ) order by coalesce(c.collected_at::date, c.collection_date) desc nulls last, c.created_at desc, c.id limit $6 offset $7

-- collection extent
with extent as ( select st_extent(c.geom) as box from collections c where c.organization_id = $1 and c.deleted_at is null and c.collection_method_id = any($2::uuid[]) and c.has_problem = true and coalesce(c.collected_at::date, c.collection_date) >= $3 and coalesce(c.collected_at::date, c.collection_date) <= $4 and exists ( select 1 from regions rf where rf.id = any($5::uuid[]) and rf.organization_id = c.organization_id and rf.deleted_at is null and rf.geom && c.geom and st_intersects(rf.geom, c.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- collection by id
select c.id, c.organization_id as "organizationId", c.trap_id as "trapId", c.lat, c.lng, c.geojson, c.geom_type as "geomType", c.collection_method_id as "collectionMethodId", c.collected_at::text as "collectedAt", c.collection_date::text as "collectionDate", c.has_problem as "hasProblem", c.is_zero_result as "isZeroResult", c.has_bycatch as "hasBycatch", c.set_by_profile_id as "setByProfileId", c.collected_by_profile_id as "collectedByProfileId", c.created_at as "createdAt", c.updated_at as "updatedAt" from collections c where c.id = $1 and c.organization_id = $2 and c.deleted_at is null limit 1

-- application tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select a.id, st_asmvtgeom( st_transform(a.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from applications a cross join bounds where a.organization_id = $9 and a.deleted_at is null and a.geom && bounds.geom_4326 and st_intersects(a.geom, bounds.geom_4326) and a.insecticide_id = any($10::uuid[]) and a.application_method_id = any($11::uuid[]) and a.applicator_profile_id = any($12::uuid[]) and a.application_date >= $13 and a.application_date <= $14 and exists ( select 1 from regions rf where rf.id = any($15::uuid[]) and rf.organization_id = a.organization_id and rf.deleted_at is null and rf.geom && a.geom and st_intersects(rf.geom, a.geom) ) ) select coalesce(st_asmvt(tile_rows, $16::text, $17, 'geom'), ''::bytea) as tile from tile_rows

-- application page
select a.id, a.organization_id as "organizationId", a.lat, a.lng, a.geojson, a.geom_type as "geomType", a.insecticide_id as "insecticideId", a.application_method_id as "applicationMethodId", a.application_date::text as "applicationDate", a.amount_applied as "amountApplied", a.application_unit_id as "applicationUnitId", a.habitat_id as "habitatId", a.applicator_profile_id as "applicatorProfileId", ap.display_name as "applicatorName", coalesce(batches.batch_names, '[]'::json) as "batchNames", a.created_at as "createdAt", a.updated_at as "updatedAt" , count(*) over()::int as "total" from applications a left join profiles ap on ap.id = a.applicator_profile_id left join lateral ( select json_agg(ib.batch_name order by ib.batch_name) as batch_names from application_batches abx join insecticide_batches ib on ib.id = abx.insecticide_batch_id where abx.application_id = a.id and abx.deleted_at is null and ib.deleted_at is null ) batches on true where a.organization_id = $1 and a.deleted_at is null and a.insecticide_id = any($2::uuid[]) and a.application_method_id = any($3::uuid[]) and a.applicator_profile_id = any($4::uuid[]) and a.application_date >= $5 and a.application_date <= $6 and exists ( select 1 from regions rf where rf.id = any($7::uuid[]) and rf.organization_id = a.organization_id and rf.deleted_at is null and rf.geom && a.geom and st_intersects(rf.geom, a.geom) ) order by a.application_date desc, a.created_at desc, a.id limit $8 offset $9

-- application extent
with extent as ( select st_extent(a.geom) as box from applications a where a.organization_id = $1 and a.deleted_at is null and a.insecticide_id = any($2::uuid[]) and a.application_method_id = any($3::uuid[]) and a.applicator_profile_id = any($4::uuid[]) and a.application_date >= $5 and a.application_date <= $6 and exists ( select 1 from regions rf where rf.id = any($7::uuid[]) and rf.organization_id = a.organization_id and rf.deleted_at is null and rf.geom && a.geom and st_intersects(rf.geom, a.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- application by id
select a.id, a.organization_id as "organizationId", a.lat, a.lng, a.geojson, a.geom_type as "geomType", a.insecticide_id as "insecticideId", a.application_method_id as "applicationMethodId", a.application_date::text as "applicationDate", a.amount_applied as "amountApplied", a.application_unit_id as "applicationUnitId", a.habitat_id as "habitatId", a.applicator_profile_id as "applicatorProfileId", ap.display_name as "applicatorName", coalesce(batches.batch_names, '[]'::json) as "batchNames", a.created_at as "createdAt", a.updated_at as "updatedAt" from applications a left join profiles ap on ap.id = a.applicator_profile_id left join lateral ( select json_agg(ib.batch_name order by ib.batch_name) as batch_names from application_batches abx join insecticide_batches ib on ib.id = abx.insecticide_batch_id where abx.application_id = a.id and abx.deleted_at is null and ib.deleted_at is null ) batches on true where a.id = $1 and a.organization_id = $2 and a.deleted_at is null limit 1

-- source reduction tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select sr.id, st_asmvtgeom( st_transform(sr.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from source_reductions sr cross join bounds where sr.organization_id = $9 and sr.deleted_at is null and sr.geom && bounds.geom_4326 and st_intersects(sr.geom, bounds.geom_4326) and sr.source_reduction_method_id = any($10::uuid[]) and sr.technician_profile_id = any($11::uuid[]) and sr.source_reduction_date >= $12 and sr.source_reduction_date <= $13 and exists ( select 1 from regions rf where rf.id = any($14::uuid[]) and rf.organization_id = sr.organization_id and rf.deleted_at is null and rf.geom && sr.geom and st_intersects(rf.geom, sr.geom) ) ) select coalesce(st_asmvt(tile_rows, $15::text, $16, 'geom'), ''::bytea) as tile from tile_rows

-- source reduction page
select sr.id, sr.organization_id as "organizationId", sr.lat, sr.lng, sr.geojson, sr.geom_type as "geomType", sr.source_reduction_method_id as "sourceReductionMethodId", sr.source_reduction_date::text as "sourceReductionDate", sr.sources_eliminated_amount as "sourcesEliminatedAmount", sr.sources_eliminated_unit_id as "sourcesEliminatedUnitId", sr.technician_profile_id as "technicianProfileId", sr.habitat_id as "habitatId", sr.inspection_id as "inspectionId", sr.created_at as "createdAt", sr.updated_at as "updatedAt" , count(*) over()::int as "total" from source_reductions sr where sr.organization_id = $1 and sr.deleted_at is null and sr.source_reduction_method_id = any($2::uuid[]) and sr.technician_profile_id = any($3::uuid[]) and sr.source_reduction_date >= $4 and sr.source_reduction_date <= $5 and exists ( select 1 from regions rf where rf.id = any($6::uuid[]) and rf.organization_id = sr.organization_id and rf.deleted_at is null and rf.geom && sr.geom and st_intersects(rf.geom, sr.geom) ) order by sr.source_reduction_date desc, sr.created_at desc, sr.id limit $7 offset $8

-- source reduction extent
with extent as ( select st_extent(sr.geom) as box from source_reductions sr where sr.organization_id = $1 and sr.deleted_at is null and sr.source_reduction_method_id = any($2::uuid[]) and sr.technician_profile_id = any($3::uuid[]) and sr.source_reduction_date >= $4 and sr.source_reduction_date <= $5 and exists ( select 1 from regions rf where rf.id = any($6::uuid[]) and rf.organization_id = sr.organization_id and rf.deleted_at is null and rf.geom && sr.geom and st_intersects(rf.geom, sr.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- source reduction by id
select sr.id, sr.organization_id as "organizationId", sr.lat, sr.lng, sr.geojson, sr.geom_type as "geomType", sr.source_reduction_method_id as "sourceReductionMethodId", sr.source_reduction_date::text as "sourceReductionDate", sr.sources_eliminated_amount as "sourcesEliminatedAmount", sr.sources_eliminated_unit_id as "sourcesEliminatedUnitId", sr.technician_profile_id as "technicianProfileId", sr.habitat_id as "habitatId", sr.inspection_id as "inspectionId", sr.created_at as "createdAt", sr.updated_at as "updatedAt" from source_reductions sr where sr.id = $1 and sr.organization_id = $2 and sr.deleted_at is null limit 1

-- biocontrol tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select ba.id, st_asmvtgeom( st_transform(ba.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from biocontrol_actions ba cross join bounds where ba.organization_id = $9 and ba.deleted_at is null and ba.geom && bounds.geom_4326 and st_intersects(ba.geom, bounds.geom_4326) and ba.biocontrol_method_id = any($10::uuid[]) and ba.technician_profile_id = any($11::uuid[]) and ba.habitat_id is not null and ba.biocontrol_date >= $12 and ba.biocontrol_date <= $13 and exists ( select 1 from regions rf where rf.id = any($14::uuid[]) and rf.organization_id = ba.organization_id and rf.deleted_at is null and rf.geom && ba.geom and st_intersects(rf.geom, ba.geom) ) ) select coalesce(st_asmvt(tile_rows, $15::text, $16, 'geom'), ''::bytea) as tile from tile_rows

-- biocontrol page
select ba.id, ba.organization_id as "organizationId", ba.lat, ba.lng, ba.geojson, ba.geom_type as "geomType", ba.biocontrol_method_id as "biocontrolMethodId", ba.biocontrol_date::text as "biocontrolDate", ba.amount_released as "amountReleased", ba.release_unit_id as "releaseUnitId", ba.technician_profile_id as "technicianProfileId", ba.habitat_id as "habitatId", ba.inspection_id as "inspectionId", ba.created_at as "createdAt", ba.updated_at as "updatedAt" , count(*) over()::int as "total" from biocontrol_actions ba where ba.organization_id = $1 and ba.deleted_at is null and ba.biocontrol_method_id = any($2::uuid[]) and ba.technician_profile_id = any($3::uuid[]) and ba.habitat_id is not null and ba.biocontrol_date >= $4 and ba.biocontrol_date <= $5 and exists ( select 1 from regions rf where rf.id = any($6::uuid[]) and rf.organization_id = ba.organization_id and rf.deleted_at is null and rf.geom && ba.geom and st_intersects(rf.geom, ba.geom) ) order by ba.biocontrol_date desc, ba.created_at desc, ba.id limit $7 offset $8

-- biocontrol extent
with extent as ( select st_extent(ba.geom) as box from biocontrol_actions ba where ba.organization_id = $1 and ba.deleted_at is null and ba.biocontrol_method_id = any($2::uuid[]) and ba.technician_profile_id = any($3::uuid[]) and ba.habitat_id is not null and ba.biocontrol_date >= $4 and ba.biocontrol_date <= $5 and exists ( select 1 from regions rf where rf.id = any($6::uuid[]) and rf.organization_id = ba.organization_id and rf.deleted_at is null and rf.geom && ba.geom and st_intersects(rf.geom, ba.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- biocontrol by id
select ba.id, ba.organization_id as "organizationId", ba.lat, ba.lng, ba.geojson, ba.geom_type as "geomType", ba.biocontrol_method_id as "biocontrolMethodId", ba.biocontrol_date::text as "biocontrolDate", ba.amount_released as "amountReleased", ba.release_unit_id as "releaseUnitId", ba.technician_profile_id as "technicianProfileId", ba.habitat_id as "habitatId", ba.inspection_id as "inspectionId", ba.created_at as "createdAt", ba.updated_at as "updatedAt" from biocontrol_actions ba where ba.id = $1 and ba.organization_id = $2 and ba.deleted_at is null limit 1

-- outreach tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select oa.id, st_asmvtgeom( st_transform(oa.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from outreach_actions oa cross join bounds where oa.organization_id = $9 and oa.deleted_at is null and oa.geom && bounds.geom_4326 and st_intersects(oa.geom, bounds.geom_4326) and oa.outreach_method_id = any($10::uuid[]) and oa.technician_profile_id = any($11::uuid[]) and oa.outreach_date >= $12 and oa.outreach_date <= $13 and exists ( select 1 from regions rf where rf.id = any($14::uuid[]) and rf.organization_id = oa.organization_id and rf.deleted_at is null and rf.geom && oa.geom and st_intersects(rf.geom, oa.geom) ) ) select coalesce(st_asmvt(tile_rows, $15::text, $16, 'geom'), ''::bytea) as tile from tile_rows

-- outreach page
select oa.id, oa.organization_id as "organizationId", oa.lat, oa.lng, oa.geojson, oa.geom_type as "geomType", oa.outreach_method_id as "outreachMethodId", oa.outreach_date::text as "outreachDate", oa.reach, oa.reach_description as "reachDescription", oa.technician_profile_id as "technicianProfileId", oa.address_id as "addressId", oa.inspection_id as "inspectionId", oa.created_at as "createdAt", oa.updated_at as "updatedAt" , count(*) over()::int as "total" from outreach_actions oa where oa.organization_id = $1 and oa.deleted_at is null and oa.outreach_method_id = any($2::uuid[]) and oa.technician_profile_id = any($3::uuid[]) and oa.outreach_date >= $4 and oa.outreach_date <= $5 and exists ( select 1 from regions rf where rf.id = any($6::uuid[]) and rf.organization_id = oa.organization_id and rf.deleted_at is null and rf.geom && oa.geom and st_intersects(rf.geom, oa.geom) ) order by oa.outreach_date desc, oa.created_at desc, oa.id limit $7 offset $8

-- outreach extent
with extent as ( select st_extent(oa.geom) as box from outreach_actions oa where oa.organization_id = $1 and oa.deleted_at is null and oa.outreach_method_id = any($2::uuid[]) and oa.technician_profile_id = any($3::uuid[]) and oa.outreach_date >= $4 and oa.outreach_date <= $5 and exists ( select 1 from regions rf where rf.id = any($6::uuid[]) and rf.organization_id = oa.organization_id and rf.deleted_at is null and rf.geom && oa.geom and st_intersects(rf.geom, oa.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- outreach by id
select oa.id, oa.organization_id as "organizationId", oa.lat, oa.lng, oa.geojson, oa.geom_type as "geomType", oa.outreach_method_id as "outreachMethodId", oa.outreach_date::text as "outreachDate", oa.reach, oa.reach_description as "reachDescription", oa.technician_profile_id as "technicianProfileId", oa.address_id as "addressId", oa.inspection_id as "inspectionId", oa.created_at as "createdAt", oa.updated_at as "updatedAt" from outreach_actions oa where oa.id = $1 and oa.organization_id = $2 and oa.deleted_at is null limit 1

-- requested control action by id
select rca.id, rca.organization_id as "organizationId", rca.lat, rca.lng, rca.geojson, rca.geom_type as "geomType", rca.updated_at as "updatedAt" from requested_control_actions rca where rca.id = $1 and rca.organization_id = $2 and rca.deleted_at is null limit 1

-- address tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select a.id, a.display_name as "displayName", st_asmvtgeom( st_transform(a.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from addresses a cross join bounds where a.organization_id = $9 and a.deleted_at is null and position(lower($10) in lower(a.display_name)) > 0 and exists ( select 1 from regions rf where rf.id = any($11::uuid[]) and rf.organization_id = a.organization_id and rf.deleted_at is null and rf.geom && a.geom and st_intersects(rf.geom, a.geom) ) and a.geom && bounds.geom_4326 and st_intersects(a.geom, bounds.geom_4326) ) select coalesce(st_asmvt(tile_rows, $12::text, $13, 'geom'), ''::bytea) as tile from tile_rows

-- address extent
with extent as ( select st_extent(a.geom) as box from addresses a where a.organization_id = $1 and a.deleted_at is null and position(lower($2) in lower(a.display_name)) > 0 and exists ( select 1 from regions rf where rf.id = any($3::uuid[]) and rf.organization_id = a.organization_id and rf.deleted_at is null and rf.geom && a.geom and st_intersects(rf.geom, a.geom) ) ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent

-- region tile
with bounds as ( select st_tileenvelope($1, $2, $3) as geom_3857, st_transform(st_tileenvelope($4, $5, $6), 4326) as geom_4326 ), tile_rows as ( select r.id, r.name, r.region_folder_id as "regionFolderId", st_asmvtgeom( st_transform(r.geom, 3857), bounds.geom_3857, extent => $7, buffer => $8 ) as geom from regions r cross join bounds where r.organization_id = $9 and r.deleted_at is null and r.id = any($10::uuid[]) and r.region_folder_id is null and position(lower($11) in lower(r.name)) > 0 and r.geom && bounds.geom_4326 and st_intersects(r.geom, bounds.geom_4326) ) select coalesce(st_asmvt(tile_rows, $12::text, $13, 'geom'), ''::bytea) as tile from tile_rows

-- region extent
with extent as ( select st_extent(r.geom) as box from regions r where r.organization_id = $1 and r.deleted_at is null and r.id = any($2::uuid[]) and r.region_folder_id is null and position(lower($3) in lower(r.name)) > 0 ) select st_xmin(box) as "west", st_ymin(box) as "south", st_xmax(box) as "east", st_ymax(box) as "north" from extent