import { randomUUID } from 'node:crypto';
import {
	type Kysely,
	type MutationWriteResult,
	type SimmerDatabase,
	sql,
	type Transaction,
} from '@simmer-mosquito/db';
import {
	type ContactReferenceInput,
	closeServiceRequestCommand,
	completeMissionNotificationCommand,
	createContactCommand,
	createNotificationRegistrationCommand,
	createServiceRequestCommand,
	DomainValidationError,
	deactivateNotificationRegistrationCommand,
	deleteContactCommand,
	deleteNotificationRegistrationCommand,
	deleteServiceRequestCommand,
	failMissionNotificationCommand,
	mergeContactsCommand,
	type NotificationRegistrationLocationInput,
	type PublicEngagementCommand,
	reactivateNotificationRegistrationCommand,
	reopenMissionNotificationCommand,
	reopenServiceRequestCommand,
	type ServiceRequestLocationInput,
	skipMissionNotificationCommand,
	subscribeNotificationRegistrationTypeCommand,
	unsubscribeNotificationRegistrationTypeCommand,
	updateContactCommunicationCommand,
	updateContactDetailsCommand,
	updateNotificationRegistrationBufferCommand,
	updateNotificationRegistrationContactCommand,
	updateNotificationRegistrationFlagsCommand,
	updateNotificationRegistrationLocationCommand,
	updateServiceRequestContactCommand,
	updateServiceRequestDetailsCommand,
	updateServiceRequestLocationCommand,
} from '@simmer-mosquito/domain';
import type { Context, Hono, MiddlewareHandler } from 'hono';
import type { AuthContext } from './auth-context.js';
import type { AuthVariables } from './auth-middleware.js';

type PublicEngagementDb = Kysely<SimmerDatabase>;
type PublicEngagementTransaction = Transaction<SimmerDatabase>;
type CommandContext = Context<{ Variables: AuthVariables }>;

type ContactReference =
	| { readonly kind: 'existing'; readonly contactId: string }
	| { readonly kind: 'new'; readonly contactId: string; readonly details: ContactDetails };

interface ContactDetails {
	readonly contactName: string | null;
	readonly preferredPhone: string | null;
	readonly alternatePhone: string | null;
	readonly email: string | null;
	readonly company: string | null;
	readonly department: string | null;
	readonly title: string | null;
	readonly wantsEmail: boolean;
	readonly wantsSms: boolean;
	readonly wantsPhone: boolean;
}

interface InlineAddressDetails {
	readonly displayName: string;
	readonly geometry: unknown;
	readonly country: string;
	readonly addressLine1: string | null;
	readonly addressLine2: string | null;
	readonly locality: string | null;
	readonly region: string | null;
	readonly postalCode: string | null;
	readonly geocoderResponse: unknown | null;
}

/**
 * Public engagement command endpoints: contacts, service requests, notification
 * registrations (+ registration-type subscriptions), and mission-notification
 * status transitions. (Notification *types* are handled separately in
 * public-engagement-commands.ts.)
 *
 * Service requests and notification registrations accept either an existing
 * contact/address reference or an inline `{ kind: 'new', ... }` payload that the
 * server materializes first. Mission notifications are generated by an automated
 * server-side flow (not wired here); only their status transitions are exposed.
 */
export function registerPublicEngagementRecordRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	registerContactRoutes(app, options);
	registerServiceRequestRoutes(app, options);
	registerNotificationRegistrationRoutes(app, options);
	registerNotificationRegistrationTypeRoutes(app, options);
	registerMissionNotificationRoutes(app, options);
}

// ===========================================================================
// Contacts
// ===========================================================================

function registerContactRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	app.post('/public-engagement/contacts', options.authContextMiddleware, async (context) => {
		const raw = await readJsonObject(context.req);
		if (!raw.ok) {
			return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
		}
		const ctx = agencyCommandContext(context.get('authContext'));
		const result = createCommand(() =>
			createContactCommand({
				...ctx,
				contactId: readText(raw.payload.id) ?? '',
				...readContactDetails(raw.payload),
			}),
		);
		if (!result.ok) {
			return context.json(result.body, 400);
		}
		return runContactCommands(context, options.db, [result.command], 201);
	});

	app.post('/public-engagement/contacts/merge', options.authContextMiddleware, async (context) => {
		const raw = await readJsonObject(context.req);
		if (!raw.ok) {
			return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
		}
		const ctx = agencyCommandContext(context.get('authContext'));
		const result = createCommand(() =>
			mergeContactsCommand({
				...ctx,
				targetContactId: readText(raw.payload.targetContactId) ?? '',
				sourceContactIds: readStringArray(raw.payload.sourceContactIds),
				acknowledgedContactMerge: true,
			}),
		);
		if (!result.ok) {
			return context.json(result.body, 400);
		}
		return runContactCommands(context, options.db, [result.command]);
	});

	app.patch(
		'/public-engagement/contacts/:contactId',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const contactId = context.req.param('contactId');
			const payload = raw.payload;
			const commands: PublicEngagementCommand[] = [];

			if (['contactName', 'company', 'department', 'title'].some((key) => key in payload)) {
				const result = createCommand(() =>
					updateContactDetailsCommand({
						...ctx,
						contactId,
						...('contactName' in payload
							? { contactName: readNullableText(payload.contactName) }
							: {}),
						...('company' in payload ? { company: readNullableText(payload.company) } : {}),
						...('department' in payload
							? { department: readNullableText(payload.department) }
							: {}),
						...('title' in payload ? { title: readNullableText(payload.title) } : {}),
					}),
				);
				if (!result.ok) return context.json(result.body, 400);
				commands.push(result.command);
			}

			const communicationKeys = [
				'preferredPhone',
				'alternatePhone',
				'email',
				'wantsEmail',
				'wantsSms',
				'wantsPhone',
			];
			if (communicationKeys.some((key) => key in payload)) {
				const result = createCommand(() =>
					updateContactCommunicationCommand({
						...ctx,
						contactId,
						...('preferredPhone' in payload
							? { preferredPhone: readNullableText(payload.preferredPhone) }
							: {}),
						...('alternatePhone' in payload
							? { alternatePhone: readNullableText(payload.alternatePhone) }
							: {}),
						...('email' in payload ? { email: readNullableText(payload.email) } : {}),
						...('wantsEmail' in payload ? { wantsEmail: payload.wantsEmail === true } : {}),
						...('wantsSms' in payload ? { wantsSms: payload.wantsSms === true } : {}),
						...('wantsPhone' in payload ? { wantsPhone: payload.wantsPhone === true } : {}),
					}),
				);
				if (!result.ok) return context.json(result.body, 400);
				commands.push(result.command);
			}

			if (commands.length === 0) {
				return context.json(invalidUpdate('contact').body, 400);
			}
			return runContactCommands(context, options.db, commands);
		},
	);

	app.delete(
		'/public-engagement/contacts/:contactId',
		options.authContextMiddleware,
		async (context) => {
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				deleteContactCommand({ ...ctx, contactId: context.req.param('contactId') }),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runContactCommands(context, options.db, [result.command]);
		},
	);
}

async function runContactCommands(
	context: CommandContext,
	db: PublicEngagementDb,
	commands: readonly PublicEngagementCommand[],
	createdStatus?: 201,
) {
	try {
		const result = await writeCommands(db, commands, writeContactCommand);
		if (result.row === null) {
			return context.json({ error: 'contact_not_found' }, 404);
		}
		return context.json({ contact: result.row, txid: result.txid }, createdStatus ?? 200);
	} catch (error) {
		return handleCommandError(context, error);
	}
}

async function writeContactCommand(
	trx: PublicEngagementTransaction,
	command: PublicEngagementCommand,
): Promise<SafeContact | null> {
	switch (command.type) {
		case 'publicEngagement.createContact': {
			const row = await insertContact(
				trx,
				command.payload.organizationId,
				command.payload.contactId,
				command.payload,
				command.payload.actorProfileId,
			);
			return row;
		}
		case 'publicEngagement.updateContactDetails':
			return updateContact(trx, command.payload.contactId, command.payload.organizationId, {
				...('contactName' in command.payload.changes
					? { contact_name: command.payload.changes.contactName ?? null }
					: {}),
				...('company' in command.payload.changes
					? { company: command.payload.changes.company ?? null }
					: {}),
				...('department' in command.payload.changes
					? { department: command.payload.changes.department ?? null }
					: {}),
				...('title' in command.payload.changes
					? { title: command.payload.changes.title ?? null }
					: {}),
				updated_by_profile_id: command.payload.actorProfileId,
			});
		case 'publicEngagement.updateContactCommunication':
			return updateContact(trx, command.payload.contactId, command.payload.organizationId, {
				...('preferredPhone' in command.payload.changes
					? { preferred_phone: command.payload.changes.preferredPhone ?? null }
					: {}),
				...('alternatePhone' in command.payload.changes
					? { alternate_phone: command.payload.changes.alternatePhone ?? null }
					: {}),
				...('email' in command.payload.changes
					? { email: command.payload.changes.email ?? null }
					: {}),
				...('wantsEmail' in command.payload.changes
					? { wants_email: command.payload.changes.wantsEmail ?? false }
					: {}),
				...('wantsSms' in command.payload.changes
					? { wants_sms: command.payload.changes.wantsSms ?? false }
					: {}),
				...('wantsPhone' in command.payload.changes
					? { wants_phone: command.payload.changes.wantsPhone ?? false }
					: {}),
				updated_by_profile_id: command.payload.actorProfileId,
			});
		case 'publicEngagement.mergeContacts': {
			for (const sourceId of command.payload.sourceContactIds) {
				await softDelete(
					trx,
					'contacts',
					sourceId,
					command.payload.organizationId,
					command.payload.actorProfileId,
					contactReturnColumns,
					toSafeContact,
				);
			}
			return loadContact(trx, command.payload.targetContactId, command.payload.organizationId);
		}
		case 'publicEngagement.deleteContact':
			return softDelete(
				trx,
				'contacts',
				command.payload.contactId,
				command.payload.organizationId,
				command.payload.actorProfileId,
				contactReturnColumns,
				toSafeContact,
			);
		default:
			throw new Error(`Unsupported contact command: ${command.type}`);
	}
}

async function insertContact(
	trx: PublicEngagementTransaction,
	organizationId: string,
	contactId: string,
	details: ContactDetails,
	actorProfileId: string,
): Promise<SafeContact> {
	const row = await trx
		.insertInto('contacts')
		.values({
			id: contactId,
			organization_id: organizationId,
			contact_name: details.contactName,
			preferred_phone: details.preferredPhone,
			alternate_phone: details.alternatePhone,
			email: details.email,
			company: details.company,
			department: details.department,
			title: details.title,
			wants_email: details.wantsEmail,
			wants_sms: details.wantsSms,
			wants_phone: details.wantsPhone,
			created_by_profile_id: actorProfileId,
			updated_by_profile_id: actorProfileId,
		})
		.returning(contactReturnColumns)
		.executeTakeFirstOrThrow();
	return toSafeContact(row);
}

async function updateContact(
	trx: PublicEngagementTransaction,
	contactId: string,
	organizationId: string,
	set: Record<string, unknown>,
): Promise<SafeContact | null> {
	return updateRow(
		trx,
		'contacts',
		contactId,
		organizationId,
		set,
		contactReturnColumns,
		toSafeContact,
	);
}

async function loadContact(
	trx: PublicEngagementTransaction,
	contactId: string,
	organizationId: string,
): Promise<SafeContact | null> {
	const row = await trx
		.selectFrom('contacts')
		.select(contactReturnColumns)
		.where('id', '=', contactId)
		.where('organization_id', '=', organizationId)
		.where('deleted_at', 'is', null)
		.executeTakeFirst();
	return row === undefined ? null : toSafeContact(row);
}

// ===========================================================================
// Service requests
// ===========================================================================

function registerServiceRequestRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	app.post(
		'/public-engagement/service-requests',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const p = raw.payload;
			const result = createCommand(() =>
				createServiceRequestCommand({
					...ctx,
					serviceRequestId: readText(p.id) ?? '',
					contact: p.contact as ContactReferenceInput,
					location: p.location as ServiceRequestLocationInput,
					intakeType: (readText(p.intakeType) ?? '') as never,
					requestDate: readText(p.requestDate) ?? '',
					details: readText(p.details) ?? '',
					receivedByProfileId: readNullableText(p.receivedByProfileId),
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runServiceRequestCommands(context, options.db, [result.command], 201);
		},
	);

	app.patch(
		'/public-engagement/service-requests/:serviceRequestId',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const commandsResult = buildServiceRequestUpdateCommands(
				context.get('authContext'),
				context.req.param('serviceRequestId'),
				raw.payload,
			);
			if (!commandsResult.ok) {
				return context.json(commandsResult.body, 400);
			}
			return runServiceRequestCommands(context, options.db, commandsResult.commands);
		},
	);

	app.post(
		'/public-engagement/service-requests/:serviceRequestId/contact',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				updateServiceRequestContactCommand({
					...ctx,
					serviceRequestId: context.req.param('serviceRequestId'),
					contact: raw.payload.contact as ContactReferenceInput,
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runServiceRequestCommands(context, options.db, [result.command]);
		},
	);

	app.post(
		'/public-engagement/service-requests/:serviceRequestId/location',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				updateServiceRequestLocationCommand({
					...ctx,
					serviceRequestId: context.req.param('serviceRequestId'),
					location: raw.payload.location as ServiceRequestLocationInput,
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runServiceRequestCommands(context, options.db, [result.command]);
		},
	);

	app.delete(
		'/public-engagement/service-requests/:serviceRequestId',
		options.authContextMiddleware,
		async (context) => {
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				deleteServiceRequestCommand({
					...ctx,
					serviceRequestId: context.req.param('serviceRequestId'),
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runServiceRequestCommands(context, options.db, [result.command]);
		},
	);
}

function buildServiceRequestUpdateCommands(
	authContext: AuthContext,
	serviceRequestId: string,
	payload: Record<string, unknown>,
): CommandsResult {
	const ctx = agencyCommandContext(authContext);
	const commands: PublicEngagementCommand[] = [];

	const detailKeys = ['requestDate', 'intakeType', 'receivedByProfileId', 'details'];
	if (detailKeys.some((key) => key in payload)) {
		const result = createCommand(() =>
			updateServiceRequestDetailsCommand({
				...ctx,
				serviceRequestId,
				...('requestDate' in payload ? { requestDate: readText(payload.requestDate) ?? '' } : {}),
				...('intakeType' in payload
					? { intakeType: (readText(payload.intakeType) ?? '') as never }
					: {}),
				...('receivedByProfileId' in payload
					? { receivedByProfileId: readNullableText(payload.receivedByProfileId) }
					: {}),
				...('details' in payload ? { details: readText(payload.details) ?? '' } : {}),
				acknowledgedClosedRequestChange: true,
			}),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if ('contactId' in payload) {
		const result = createCommand(() =>
			updateServiceRequestContactCommand({
				...ctx,
				serviceRequestId,
				contact: { kind: 'existing', contactId: readText(payload.contactId) ?? '' },
			}),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if ('closedAt' in payload) {
		const closedAt = readDate(payload.closedAt);
		const result = createCommand(() =>
			closedAt !== null
				? closeServiceRequestCommand({
						...ctx,
						serviceRequestId,
						resolutionCommentId: randomUUID(),
						resolutionSummary: readText(payload.resolutionSummary) ?? 'Closed',
						closedAt,
					})
				: reopenServiceRequestCommand({
						...ctx,
						serviceRequestId,
						reopenCommentId: randomUUID(),
						reopenReason: 'Reopened',
					}),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if (commands.length === 0) {
		return invalidUpdate('service request');
	}
	return { ok: true, commands };
}

async function runServiceRequestCommands(
	context: CommandContext,
	db: PublicEngagementDb,
	commands: readonly PublicEngagementCommand[],
	createdStatus?: 201,
) {
	try {
		const result = await writeCommands(db, commands, writeServiceRequestCommand);
		if (result.row === null) {
			return context.json({ error: 'service_request_not_found' }, 404);
		}
		return context.json({ serviceRequest: result.row, txid: result.txid }, createdStatus ?? 200);
	} catch (error) {
		return handleCommandError(context, error);
	}
}

async function writeServiceRequestCommand(
	trx: PublicEngagementTransaction,
	command: PublicEngagementCommand,
): Promise<SafeServiceRequest | null> {
	switch (command.type) {
		case 'publicEngagement.createServiceRequest': {
			const contactId = await resolveContact(
				trx,
				command.payload.organizationId,
				command.payload.contact,
				command.payload.actorProfileId,
			);
			const addressId = await resolveServiceRequestAddress(
				trx,
				command.payload.organizationId,
				command.payload.location.address,
				command.payload.actorProfileId,
			);
			const row = await trx
				.insertInto('service_requests')
				.values({
					id: command.payload.serviceRequestId,
					organization_id: command.payload.organizationId,
					intake_type: command.payload.intakeType,
					request_date: localDateColumn(command.payload.requestDate),
					geom: geojsonToGeom(command.payload.location.geometry),
					address_id: addressId,
					contact_id: contactId,
					received_by_profile_id: command.payload.receivedByProfileId,
					details: command.payload.details,
					created_by_profile_id: command.payload.actorProfileId,
					updated_by_profile_id: command.payload.actorProfileId,
				})
				.returning(serviceRequestReturnColumns)
				.executeTakeFirstOrThrow();
			return toSafeServiceRequest(row);
		}
		case 'publicEngagement.updateServiceRequestDetails':
			return updateServiceRequest(
				trx,
				command.payload.serviceRequestId,
				command.payload.organizationId,
				{
					...('requestDate' in command.payload.changes &&
					command.payload.changes.requestDate !== undefined
						? { request_date: localDateColumn(command.payload.changes.requestDate) }
						: {}),
					...('intakeType' in command.payload.changes
						? { intake_type: command.payload.changes.intakeType }
						: {}),
					...('receivedByProfileId' in command.payload.changes
						? { received_by_profile_id: command.payload.changes.receivedByProfileId ?? null }
						: {}),
					...('details' in command.payload.changes
						? { details: command.payload.changes.details }
						: {}),
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.updateServiceRequestContact': {
			const contactId = await resolveContact(
				trx,
				command.payload.organizationId,
				command.payload.contact,
				command.payload.actorProfileId,
			);
			return updateServiceRequest(
				trx,
				command.payload.serviceRequestId,
				command.payload.organizationId,
				{
					contact_id: contactId,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		}
		case 'publicEngagement.updateServiceRequestLocation': {
			const addressId = await resolveServiceRequestAddress(
				trx,
				command.payload.organizationId,
				command.payload.location.address,
				command.payload.actorProfileId,
			);
			return updateServiceRequest(
				trx,
				command.payload.serviceRequestId,
				command.payload.organizationId,
				{
					geom: geojsonToGeom(command.payload.location.geometry),
					address_id: addressId,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		}
		case 'publicEngagement.closeServiceRequest':
			return updateServiceRequest(
				trx,
				command.payload.serviceRequestId,
				command.payload.organizationId,
				{
					closed_at: command.payload.closedAt === null ? sql`now()` : command.payload.closedAt,
					closed_by_profile_id: command.payload.actorProfileId,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.reopenServiceRequest':
			return updateServiceRequest(
				trx,
				command.payload.serviceRequestId,
				command.payload.organizationId,
				{
					closed_at: null,
					closed_by_profile_id: null,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.deleteServiceRequest':
			return softDelete(
				trx,
				'service_requests',
				command.payload.serviceRequestId,
				command.payload.organizationId,
				command.payload.actorProfileId,
				serviceRequestReturnColumns,
				toSafeServiceRequest,
			);
		default:
			throw new Error(`Unsupported service request command: ${command.type}`);
	}
}

async function updateServiceRequest(
	trx: PublicEngagementTransaction,
	serviceRequestId: string,
	organizationId: string,
	set: Record<string, unknown>,
): Promise<SafeServiceRequest | null> {
	return updateRow(
		trx,
		'service_requests',
		serviceRequestId,
		organizationId,
		set,
		serviceRequestReturnColumns,
		toSafeServiceRequest,
	);
}

// ===========================================================================
// Notification registrations
// ===========================================================================

function registerNotificationRegistrationRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	app.post(
		'/public-engagement/notification-registrations',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const p = raw.payload;
			const result = createCommand(() =>
				createNotificationRegistrationCommand({
					...ctx,
					notificationRegistrationId: readText(p.id) ?? '',
					contact: p.contact as ContactReferenceInput,
					location: p.location as NotificationRegistrationLocationInput,
					bufferDistance: readNumberOrNull(p.bufferDistance),
					bufferUnitId: readNullableText(p.bufferUnitId),
					hasBees: p.hasBees === true,
					isNoSpray: p.isNoSpray === true,
					subscriptions: readSubscriptions(p.subscriptions),
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runRegistrationCommands(context, options.db, [result.command], 201);
		},
	);

	app.patch(
		'/public-engagement/notification-registrations/:notificationRegistrationId',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const commandsResult = buildRegistrationUpdateCommands(
				context.get('authContext'),
				context.req.param('notificationRegistrationId'),
				raw.payload,
			);
			if (!commandsResult.ok) {
				return context.json(commandsResult.body, 400);
			}
			return runRegistrationCommands(context, options.db, commandsResult.commands);
		},
	);

	app.post(
		'/public-engagement/notification-registrations/:notificationRegistrationId/contact',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				updateNotificationRegistrationContactCommand({
					...ctx,
					notificationRegistrationId: context.req.param('notificationRegistrationId'),
					contact: raw.payload.contact as ContactReferenceInput,
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runRegistrationCommands(context, options.db, [result.command]);
		},
	);

	app.post(
		'/public-engagement/notification-registrations/:notificationRegistrationId/location',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				updateNotificationRegistrationLocationCommand({
					...ctx,
					notificationRegistrationId: context.req.param('notificationRegistrationId'),
					location: raw.payload.location as NotificationRegistrationLocationInput,
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runRegistrationCommands(context, options.db, [result.command]);
		},
	);

	app.delete(
		'/public-engagement/notification-registrations/:notificationRegistrationId',
		options.authContextMiddleware,
		async (context) => {
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				deleteNotificationRegistrationCommand({
					...ctx,
					notificationRegistrationId: context.req.param('notificationRegistrationId'),
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runRegistrationCommands(context, options.db, [result.command]);
		},
	);
}

function buildRegistrationUpdateCommands(
	authContext: AuthContext,
	notificationRegistrationId: string,
	payload: Record<string, unknown>,
): CommandsResult {
	const ctx = agencyCommandContext(authContext);
	const commands: PublicEngagementCommand[] = [];

	if ('hasBees' in payload || 'isNoSpray' in payload) {
		const result = createCommand(() =>
			updateNotificationRegistrationFlagsCommand({
				...ctx,
				notificationRegistrationId,
				...('hasBees' in payload ? { hasBees: payload.hasBees === true } : {}),
				...('isNoSpray' in payload ? { isNoSpray: payload.isNoSpray === true } : {}),
			}),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if ('bufferDistance' in payload || 'bufferUnitId' in payload) {
		const result = createCommand(() =>
			updateNotificationRegistrationBufferCommand({
				...ctx,
				notificationRegistrationId,
				bufferDistance: readNumberOrNull(payload.bufferDistance),
				bufferUnitId: readNullableText(payload.bufferUnitId),
			}),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if ('contactId' in payload) {
		const result = createCommand(() =>
			updateNotificationRegistrationContactCommand({
				...ctx,
				notificationRegistrationId,
				contact: { kind: 'existing', contactId: readText(payload.contactId) ?? '' },
			}),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if (typeof payload.isActive === 'boolean') {
		const result = createCommand(() =>
			payload.isActive
				? reactivateNotificationRegistrationCommand({ ...ctx, notificationRegistrationId })
				: deactivateNotificationRegistrationCommand({ ...ctx, notificationRegistrationId }),
		);
		if (!result.ok) return result;
		commands.push(result.command);
	}

	if (commands.length === 0) {
		return invalidUpdate('notification registration');
	}
	return { ok: true, commands };
}

async function runRegistrationCommands(
	context: CommandContext,
	db: PublicEngagementDb,
	commands: readonly PublicEngagementCommand[],
	createdStatus?: 201,
) {
	try {
		const result = await writeCommands(db, commands, writeRegistrationCommand);
		if (result.row === null) {
			return context.json({ error: 'notification_registration_not_found' }, 404);
		}
		return context.json(
			{ notificationRegistration: result.row, txid: result.txid },
			createdStatus ?? 200,
		);
	} catch (error) {
		return handleCommandError(context, error);
	}
}

async function writeRegistrationCommand(
	trx: PublicEngagementTransaction,
	command: PublicEngagementCommand,
): Promise<SafeRegistration | null> {
	switch (command.type) {
		case 'publicEngagement.createNotificationRegistration': {
			const contactId = await resolveContact(
				trx,
				command.payload.organizationId,
				command.payload.contact,
				command.payload.actorProfileId,
			);
			const addressId = await resolveNotificationAddress(
				trx,
				command.payload.organizationId,
				command.payload.location.address,
				command.payload.actorProfileId,
			);
			const row = await trx
				.insertInto('notification_registrations')
				.values({
					id: command.payload.notificationRegistrationId,
					organization_id: command.payload.organizationId,
					contact_id: contactId,
					geom: geojsonToGeom(command.payload.location.geometry),
					address_id: addressId,
					buffer_distance: command.payload.bufferDistance,
					buffer_unit_id: command.payload.bufferUnitId,
					has_bees: command.payload.hasBees,
					is_no_spray: command.payload.isNoSpray,
					is_active: true,
					created_by_profile_id: command.payload.actorProfileId,
					updated_by_profile_id: command.payload.actorProfileId,
				})
				.returning(registrationReturnColumns)
				.executeTakeFirstOrThrow();
			for (const subscription of command.payload.subscriptions) {
				await insertRegistrationType(
					trx,
					command.payload.organizationId,
					subscription.notificationRegistrationTypeId,
					command.payload.notificationRegistrationId,
					subscription.notificationTypeId,
					command.payload.actorProfileId,
				);
			}
			return toSafeRegistration(row);
		}
		case 'publicEngagement.updateNotificationRegistrationContact': {
			const contactId = await resolveContact(
				trx,
				command.payload.organizationId,
				command.payload.contact,
				command.payload.actorProfileId,
			);
			return updateRegistration(
				trx,
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				{
					contact_id: contactId,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		}
		case 'publicEngagement.updateNotificationRegistrationLocation': {
			const addressId = await resolveNotificationAddress(
				trx,
				command.payload.organizationId,
				command.payload.location.address,
				command.payload.actorProfileId,
			);
			return updateRegistration(
				trx,
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				{
					geom: geojsonToGeom(command.payload.location.geometry),
					address_id: addressId,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		}
		case 'publicEngagement.updateNotificationRegistrationBuffer':
			return updateRegistration(
				trx,
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				{
					buffer_distance: command.payload.bufferDistance,
					buffer_unit_id: command.payload.bufferUnitId,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.updateNotificationRegistrationFlags':
			return updateRegistration(
				trx,
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				{
					...('hasBees' in command.payload.changes
						? { has_bees: command.payload.changes.hasBees ?? false }
						: {}),
					...('isNoSpray' in command.payload.changes
						? { is_no_spray: command.payload.changes.isNoSpray ?? false }
						: {}),
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.deactivateNotificationRegistration':
			return updateRegistration(
				trx,
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				{
					is_active: false,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.reactivateNotificationRegistration':
			return updateRegistration(
				trx,
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				{
					is_active: true,
					updated_by_profile_id: command.payload.actorProfileId,
				},
			);
		case 'publicEngagement.deleteNotificationRegistration':
			return softDelete(
				trx,
				'notification_registrations',
				command.payload.notificationRegistrationId,
				command.payload.organizationId,
				command.payload.actorProfileId,
				registrationReturnColumns,
				toSafeRegistration,
			);
		default:
			throw new Error(`Unsupported notification registration command: ${command.type}`);
	}
}

async function updateRegistration(
	trx: PublicEngagementTransaction,
	notificationRegistrationId: string,
	organizationId: string,
	set: Record<string, unknown>,
): Promise<SafeRegistration | null> {
	return updateRow(
		trx,
		'notification_registrations',
		notificationRegistrationId,
		organizationId,
		set,
		registrationReturnColumns,
		toSafeRegistration,
	);
}

// ===========================================================================
// Notification registration types (subscriptions)
// ===========================================================================

function registerNotificationRegistrationTypeRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	app.post(
		'/public-engagement/notification-registration-types',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				subscribeNotificationRegistrationTypeCommand({
					...ctx,
					notificationRegistrationTypeId: readText(raw.payload.id) ?? '',
					notificationRegistrationId: readText(raw.payload.notificationRegistrationId) ?? '',
					notificationTypeId: readText(raw.payload.notificationTypeId) ?? '',
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runRegistrationTypeCommands(context, options.db, [result.command], 201);
		},
	);

	app.delete(
		'/public-engagement/notification-registration-types/:notificationRegistrationTypeId',
		options.authContextMiddleware,
		async (context) => {
			const ctx = agencyCommandContext(context.get('authContext'));
			const result = createCommand(() =>
				unsubscribeNotificationRegistrationTypeCommand({
					...ctx,
					notificationRegistrationTypeId: context.req.param('notificationRegistrationTypeId'),
				}),
			);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			return runRegistrationTypeCommands(context, options.db, [result.command]);
		},
	);
}

async function runRegistrationTypeCommands(
	context: CommandContext,
	db: PublicEngagementDb,
	commands: readonly PublicEngagementCommand[],
	createdStatus?: 201,
) {
	try {
		const result = await writeCommands(db, commands, writeRegistrationTypeCommand);
		if (result.row === null) {
			return context.json({ error: 'notification_registration_type_not_found' }, 404);
		}
		return context.json(
			{ notificationRegistrationType: result.row, txid: result.txid },
			createdStatus ?? 200,
		);
	} catch (error) {
		return handleCommandError(context, error);
	}
}

async function writeRegistrationTypeCommand(
	trx: PublicEngagementTransaction,
	command: PublicEngagementCommand,
): Promise<SafeRegistrationType | null> {
	switch (command.type) {
		case 'publicEngagement.subscribeNotificationRegistrationType':
			return insertRegistrationType(
				trx,
				command.payload.organizationId,
				command.payload.notificationRegistrationTypeId,
				command.payload.notificationRegistrationId,
				command.payload.notificationTypeId,
				command.payload.actorProfileId,
			);
		case 'publicEngagement.unsubscribeNotificationRegistrationType':
			return softDelete(
				trx,
				'notification_registration_types',
				command.payload.notificationRegistrationTypeId,
				command.payload.organizationId,
				command.payload.actorProfileId,
				registrationTypeReturnColumns,
				toSafeRegistrationType,
			);
		default:
			throw new Error(`Unsupported registration type command: ${command.type}`);
	}
}

async function insertRegistrationType(
	trx: PublicEngagementTransaction,
	organizationId: string,
	notificationRegistrationTypeId: string,
	notificationRegistrationId: string,
	notificationTypeId: string,
	actorProfileId: string,
): Promise<SafeRegistrationType> {
	const row = await trx
		.insertInto('notification_registration_types')
		.values({
			id: notificationRegistrationTypeId,
			organization_id: organizationId,
			notification_registration_id: notificationRegistrationId,
			notification_type_id: notificationTypeId,
			created_by_profile_id: actorProfileId,
			updated_by_profile_id: actorProfileId,
		})
		.returning(registrationTypeReturnColumns)
		.executeTakeFirstOrThrow();
	return toSafeRegistrationType(row);
}

// ===========================================================================
// Mission notifications (status transitions)
// ===========================================================================

function registerMissionNotificationRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	app.patch(
		'/public-engagement/mission-notifications/:missionNotificationId',
		options.authContextMiddleware,
		async (context) => {
			const raw = await readJsonObject(context.req);
			if (!raw.ok) {
				return context.json({ error: 'invalid_payload', reason: raw.reason }, 400);
			}
			const ctx = agencyCommandContext(context.get('authContext'));
			const missionNotificationId = context.req.param('missionNotificationId');
			const status = readText(raw.payload.status);
			const statusChangedAt = readDate(raw.payload.statusChangedAt);
			const build = () => {
				const base = {
					...ctx,
					missionNotificationId,
					...(statusChangedAt === null ? {} : { statusChangedAt }),
				};
				switch (status) {
					case 'completed':
						return completeMissionNotificationCommand(base);
					case 'failed':
						return failMissionNotificationCommand(base);
					case 'skipped':
						return skipMissionNotificationCommand(base);
					default:
						return reopenMissionNotificationCommand(base);
				}
			};
			const result = createCommand(build);
			if (!result.ok) {
				return context.json(result.body, 400);
			}
			try {
				const writeResult = await writeCommands(
					options.db,
					[result.command],
					writeMissionNotificationCommand,
				);
				if (writeResult.row === null) {
					return context.json({ error: 'mission_notification_not_found' }, 404);
				}
				return context.json({ missionNotification: writeResult.row, txid: writeResult.txid });
			} catch (error) {
				return handleCommandError(context, error);
			}
		},
	);
}

async function writeMissionNotificationCommand(
	trx: PublicEngagementTransaction,
	command: PublicEngagementCommand,
): Promise<SafeMissionNotification | null> {
	const statusByType: Record<string, 'completed' | 'failed' | 'skipped' | 'pending'> = {
		'publicEngagement.completeMissionNotification': 'completed',
		'publicEngagement.failMissionNotification': 'failed',
		'publicEngagement.skipMissionNotification': 'skipped',
		'publicEngagement.reopenMissionNotification': 'pending',
	};
	const status = statusByType[command.type];
	if (
		status === undefined ||
		!('missionNotificationId' in command.payload) ||
		!('statusChangedAt' in command.payload)
	) {
		throw new Error(`Unsupported mission notification command: ${command.type}`);
	}
	const payload = command.payload as {
		readonly missionNotificationId: string;
		readonly organizationId: string;
		readonly actorProfileId: string;
		readonly statusChangedAt: Date | null;
	};
	const row = await trx
		.updateTable('mission_notifications')
		.set({
			status,
			status_changed_at: payload.statusChangedAt === null ? sql`now()` : payload.statusChangedAt,
			status_changed_by_profile_id: payload.actorProfileId,
			updated_by_profile_id: payload.actorProfileId,
			updated_at: sql`now()`,
		})
		.where('id', '=', payload.missionNotificationId)
		.where('organization_id', '=', payload.organizationId)
		.where('deleted_at', 'is', null)
		.returning(missionNotificationReturnColumns)
		.executeTakeFirst();
	return row === undefined ? null : toSafeMissionNotification(row);
}

// ===========================================================================
// Inline contact / address resolution
// ===========================================================================

async function resolveContact(
	trx: PublicEngagementTransaction,
	organizationId: string,
	contact: ContactReference,
	actorProfileId: string,
): Promise<string> {
	if (contact.kind === 'new') {
		await insertContact(trx, organizationId, contact.contactId, contact.details, actorProfileId);
		return contact.contactId;
	}
	return contact.contactId;
}

type AddressReference =
	| { readonly kind: 'none' }
	| { readonly kind: 'existing'; readonly addressId: string }
	| { readonly kind: 'new'; readonly addressId: string; readonly details: InlineAddressDetails };

async function resolveServiceRequestAddress(
	trx: PublicEngagementTransaction,
	organizationId: string,
	address: AddressReference,
	actorProfileId: string,
): Promise<string> {
	if (address.kind === 'new') {
		await insertAddress(trx, organizationId, address.addressId, address.details, actorProfileId);
		return address.addressId;
	}
	if (address.kind === 'existing') {
		return address.addressId;
	}
	throw new CommandError(400, { error: 'service_request_address_required' });
}

async function resolveNotificationAddress(
	trx: PublicEngagementTransaction,
	organizationId: string,
	address: AddressReference,
	actorProfileId: string,
): Promise<string | null> {
	if (address.kind === 'new') {
		await insertAddress(trx, organizationId, address.addressId, address.details, actorProfileId);
		return address.addressId;
	}
	if (address.kind === 'existing') {
		return address.addressId;
	}
	return null;
}

async function insertAddress(
	trx: PublicEngagementTransaction,
	organizationId: string,
	addressId: string,
	details: InlineAddressDetails,
	actorProfileId: string,
): Promise<void> {
	await trx
		.insertInto('addresses')
		.values({
			id: addressId,
			organization_id: organizationId,
			geom: geojsonToGeom(details.geometry),
			display_name: details.displayName,
			country: details.country,
			address_line_1: details.addressLine1,
			address_line_2: details.addressLine2,
			locality: details.locality,
			region: details.region,
			postal_code: details.postalCode,
			geocoder_response: details.geocoderResponse,
			created_by_profile_id: actorProfileId,
			updated_by_profile_id: actorProfileId,
		})
		.execute();
}

// ===========================================================================
// Generic row helpers
// ===========================================================================

type WriteTable =
	| 'contacts'
	| 'service_requests'
	| 'notification_registrations'
	| 'notification_registration_types';

async function updateRow<TRow, TSafe>(
	trx: PublicEngagementTransaction,
	table: WriteTable,
	id: string,
	organizationId: string,
	set: Record<string, unknown>,
	columns: readonly string[],
	toSafe: (row: TRow) => TSafe,
): Promise<TSafe | null> {
	const row = await trx
		.updateTable(table)
		.set({ ...set, updated_at: sql`now()` } as never)
		.where('id', '=', id)
		.where('organization_id', '=', organizationId)
		.where('deleted_at', 'is', null)
		.returning(columns as never)
		.executeTakeFirst();
	return row === undefined ? null : toSafe(row as TRow);
}

async function softDelete<TRow, TSafe>(
	trx: PublicEngagementTransaction,
	table: WriteTable,
	id: string,
	organizationId: string,
	actorProfileId: string,
	columns: readonly string[],
	toSafe: (row: TRow) => TSafe,
): Promise<TSafe | null> {
	const row = await trx
		.updateTable(table)
		.set({
			deleted_at: sql`now()`,
			deleted_by_profile_id: actorProfileId,
			updated_by_profile_id: actorProfileId,
			updated_at: sql`now()`,
		} as never)
		.where('id', '=', id)
		.where('organization_id', '=', organizationId)
		.where('deleted_at', 'is', null)
		.returning(columns as never)
		.executeTakeFirst();
	return row === undefined ? null : toSafe(row as TRow);
}

async function writeCommands<TSafe>(
	db: PublicEngagementDb,
	commands: readonly PublicEngagementCommand[],
	write: (
		trx: PublicEngagementTransaction,
		command: PublicEngagementCommand,
	) => Promise<TSafe | null>,
): Promise<MutationWriteResult<TSafe | null>> {
	return db.transaction().execute(async (trx) => {
		let row: TSafe | null = null;
		for (const command of commands) {
			row = await write(trx, command);
		}
		return { row, txid: await readCurrentTransactionId(trx) };
	});
}

// ===========================================================================
// Response shaping
// ===========================================================================

const contactReturnColumns = [
	'id',
	'organization_id',
	'contact_name',
	'preferred_phone',
	'alternate_phone',
	'email',
	'company',
	'department',
	'title',
	'wants_email',
	'wants_sms',
	'wants_phone',
	'created_at',
	'updated_at',
] as const;

interface SafeContact {
	readonly id: string;
	readonly organizationId: string;
	readonly contactName: string | null;
	readonly email: string | null;
	readonly createdAt: Date;
	readonly updatedAt: Date;
}

function toSafeContact(row: {
	readonly id: string;
	readonly organization_id: string;
	readonly contact_name: string | null;
	readonly email: string | null;
	readonly created_at: Date;
	readonly updated_at: Date;
}): SafeContact {
	return {
		id: row.id,
		organizationId: row.organization_id,
		contactName: row.contact_name,
		email: row.email,
		createdAt: row.created_at,
		updatedAt: row.updated_at,
	};
}

const serviceRequestReturnColumns = [
	'id',
	'organization_id',
	'intake_type',
	'address_id',
	'contact_id',
	'closed_at',
	'created_at',
	'updated_at',
] as const;

interface SafeServiceRequest {
	readonly id: string;
	readonly organizationId: string;
	readonly contactId: string;
	readonly addressId: string;
	readonly closedAt: Date | null;
	readonly createdAt: Date;
	readonly updatedAt: Date;
}

function toSafeServiceRequest(row: {
	readonly id: string;
	readonly organization_id: string;
	readonly contact_id: string;
	readonly address_id: string;
	readonly closed_at: Date | null;
	readonly created_at: Date;
	readonly updated_at: Date;
}): SafeServiceRequest {
	return {
		id: row.id,
		organizationId: row.organization_id,
		contactId: row.contact_id,
		addressId: row.address_id,
		closedAt: row.closed_at,
		createdAt: row.created_at,
		updatedAt: row.updated_at,
	};
}

const registrationReturnColumns = [
	'id',
	'organization_id',
	'contact_id',
	'address_id',
	'buffer_distance',
	'buffer_unit_id',
	'has_bees',
	'is_no_spray',
	'is_active',
	'created_at',
	'updated_at',
] as const;

interface SafeRegistration {
	readonly id: string;
	readonly organizationId: string;
	readonly contactId: string;
	readonly isActive: boolean;
	readonly createdAt: Date;
	readonly updatedAt: Date;
}

function toSafeRegistration(row: {
	readonly id: string;
	readonly organization_id: string;
	readonly contact_id: string;
	readonly is_active: boolean;
	readonly created_at: Date;
	readonly updated_at: Date;
}): SafeRegistration {
	return {
		id: row.id,
		organizationId: row.organization_id,
		contactId: row.contact_id,
		isActive: row.is_active,
		createdAt: row.created_at,
		updatedAt: row.updated_at,
	};
}

const registrationTypeReturnColumns = [
	'id',
	'organization_id',
	'notification_registration_id',
	'notification_type_id',
	'created_at',
	'updated_at',
] as const;

interface SafeRegistrationType {
	readonly id: string;
	readonly organizationId: string;
	readonly notificationRegistrationId: string;
	readonly notificationTypeId: string;
	readonly createdAt: Date;
	readonly updatedAt: Date;
}

function toSafeRegistrationType(row: {
	readonly id: string;
	readonly organization_id: string;
	readonly notification_registration_id: string;
	readonly notification_type_id: string;
	readonly created_at: Date;
	readonly updated_at: Date;
}): SafeRegistrationType {
	return {
		id: row.id,
		organizationId: row.organization_id,
		notificationRegistrationId: row.notification_registration_id,
		notificationTypeId: row.notification_type_id,
		createdAt: row.created_at,
		updatedAt: row.updated_at,
	};
}

const missionNotificationReturnColumns = [
	'id',
	'organization_id',
	'mission_id',
	'status',
	'status_changed_at',
	'created_at',
	'updated_at',
] as const;

interface SafeMissionNotification {
	readonly id: string;
	readonly organizationId: string;
	readonly missionId: string;
	readonly status: string;
	readonly statusChangedAt: Date | null;
	readonly createdAt: Date;
	readonly updatedAt: Date;
}

function toSafeMissionNotification(row: {
	readonly id: string;
	readonly organization_id: string;
	readonly mission_id: string;
	readonly status: string;
	readonly status_changed_at: Date | null;
	readonly created_at: Date;
	readonly updated_at: Date;
}): SafeMissionNotification {
	return {
		id: row.id,
		organizationId: row.organization_id,
		missionId: row.mission_id,
		status: row.status,
		statusChangedAt: row.status_changed_at,
		createdAt: row.created_at,
		updatedAt: row.updated_at,
	};
}

// ===========================================================================
// Shared command + request helpers
// ===========================================================================

interface RouteOptions {
	readonly db: PublicEngagementDb;
	readonly authContextMiddleware: MiddlewareHandler<{ Variables: AuthVariables }>;
}

type CommandsResult =
	| { readonly ok: true; readonly commands: readonly PublicEngagementCommand[] }
	| { readonly ok: false; readonly body: InvalidCommandBody };

class CommandError extends Error {
	constructor(
		readonly status: 400 | 404,
		readonly body: { readonly error: string },
	) {
		super(body.error);
	}
}

function handleCommandError(context: CommandContext, error: unknown) {
	if (error instanceof CommandError) {
		return context.json(error.body, error.status);
	}
	throw error;
}

type InvalidCommandBody = {
	readonly error: 'invalid_command';
	readonly message: string;
	readonly issues: readonly { readonly path: string; readonly message: string }[];
};

function createCommand<TCommand extends PublicEngagementCommand>(
	build: () => TCommand,
):
	| { readonly ok: true; readonly command: TCommand }
	| { readonly ok: false; readonly body: InvalidCommandBody } {
	try {
		return { ok: true, command: build() };
	} catch (error) {
		if (error instanceof DomainValidationError) {
			return {
				ok: false,
				body: { error: 'invalid_command', message: error.message, issues: error.issues },
			};
		}
		throw error;
	}
}

function invalidUpdate(changeNoun: string): {
	readonly ok: false;
	readonly body: InvalidCommandBody;
} {
	const message = `At least one ${changeNoun} field must change.`;
	return {
		ok: false,
		body: { error: 'invalid_command', message, issues: [{ path: 'changes', message }] },
	};
}

function agencyCommandContext(authContext: AuthContext) {
	return {
		organizationId: authContext.organization.id,
		actorProfileId: authContext.profile.id,
	};
}

function readContactDetails(payload: Record<string, unknown>) {
	return {
		contactName: readNullableText(payload.contactName),
		preferredPhone: readNullableText(payload.preferredPhone),
		alternatePhone: readNullableText(payload.alternatePhone),
		email: readNullableText(payload.email),
		company: readNullableText(payload.company),
		department: readNullableText(payload.department),
		title: readNullableText(payload.title),
		wantsEmail: payload.wantsEmail === true,
		wantsSms: payload.wantsSms === true,
		wantsPhone: payload.wantsPhone === true,
	};
}

function readSubscriptions(value: unknown): readonly {
	readonly notificationRegistrationTypeId: string;
	readonly notificationTypeId: string;
}[] {
	if (!Array.isArray(value)) {
		return [];
	}
	return value.map((entry) => ({
		notificationRegistrationTypeId: isRecord(entry)
			? (readText(entry.notificationRegistrationTypeId) ?? '')
			: '',
		notificationTypeId: isRecord(entry) ? (readText(entry.notificationTypeId) ?? '') : '',
	}));
}

function geojsonToGeom(geojson: unknown) {
	const serialized = JSON.stringify(geojson);
	return sql<string>`st_force2d(st_setsrid(st_geomfromgeojson(
		case
			when (${serialized}::jsonb -> 'geometry') is not null
				then (${serialized}::jsonb -> 'geometry')::text
			else ${serialized}
		end
	), 4326))`;
}

function localDateColumn(value: string) {
	return sql<Date>`${value}::date`;
}

async function readCurrentTransactionId(trx: PublicEngagementTransaction): Promise<number> {
	const result = await sql<{
		txid: string;
	}>`select pg_current_xact_id()::xid::text as txid`.execute(trx);
	const txid = result.rows[0]?.txid;
	if (txid === undefined) {
		throw new Error('Unable to read current transaction id.');
	}
	return Number.parseInt(txid, 10);
}

type JsonResult =
	| { readonly ok: true; readonly payload: Record<string, unknown> }
	| { readonly ok: false; readonly reason: string };

async function readJsonObject(request: {
	readonly json: () => Promise<unknown>;
}): Promise<JsonResult> {
	let raw: unknown;
	try {
		raw = await request.json();
	} catch {
		return { ok: false, reason: 'Request body must be JSON.' };
	}
	if (!isRecord(raw)) {
		return { ok: false, reason: 'Request body must be an object.' };
	}
	return { ok: true, payload: raw };
}

function readText(value: unknown): string | null {
	if (typeof value !== 'string') {
		return null;
	}
	const trimmed = value.trim();
	return trimmed.length === 0 ? null : trimmed;
}

function readNullableText(value: unknown): string | null {
	return readText(value);
}

function readNumberOrNull(value: unknown): number | null {
	return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function readDate(value: unknown): Date | null {
	if (typeof value !== 'string' && !(value instanceof Date)) {
		return null;
	}
	const date = value instanceof Date ? value : new Date(value);
	return Number.isNaN(date.getTime()) ? null : date;
}

function readStringArray(value: unknown): readonly string[] {
	return Array.isArray(value)
		? value.filter((entry): entry is string => typeof entry === 'string')
		: [];
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}
