// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const AdditionalPersonnelBaseRowSchema = z.object({
	aerial_inspection_id: z.uuid().nullable(),
	application_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	flight_id: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	inspection_id: z.uuid().nullable(),
	parent_table_name: z.string().nullable(),
	personnel_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type AdditionalPersonnelBaseRow = z.infer<typeof AdditionalPersonnelBaseRowSchema>;

export const AdditionalPersonnelInsertSchema = z.object({
	aerial_inspection_id: z.uuid().nullable(),
	application_id: z.uuid().nullable(),
	flight_id: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	inspection_id: z.uuid().nullable(),
	parent_table_name: z.string().nullable(),
	personnel_id: z.uuid(),
});

export type AdditionalPersonnelInsert = z.infer<typeof AdditionalPersonnelInsertSchema>;

export const AdditionalPersonnelUpdateSchema = AdditionalPersonnelInsertSchema.omit({ id: true }).partial();

export type AdditionalPersonnelUpdate = z.infer<typeof AdditionalPersonnelUpdateSchema>;
