// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const AddressTagsBaseRowSchema = z.object({
	address_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	tag_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type AddressTagsBaseRow = z.infer<typeof AddressTagsBaseRowSchema>;

export const AddressTagsInsertSchema = z.object({
	address_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
	tag_id: z.uuid(),
});

export type AddressTagsInsert = z.infer<typeof AddressTagsInsertSchema>;

export const AddressTagsUpdateSchema = AddressTagsInsertSchema.omit({ id: true }).partial();

export type AddressTagsUpdate = z.infer<typeof AddressTagsUpdateSchema>;
