// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const AddressesBaseRowSchema = z.object({
	address_fields: z.unknown(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	display_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	lat: z.number(),
	lng: z.number(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type AddressesBaseRow = z.infer<typeof AddressesBaseRowSchema>;

export const AddressesInsertSchema = z.object({
	address_fields: z.unknown(),
	display_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	lat: z.number(),
	lng: z.number(),
});

export type AddressesInsert = z.infer<typeof AddressesInsertSchema>;

export const AddressesUpdateSchema = AddressesInsertSchema.omit({ id: true }).partial();

export type AddressesUpdate = z.infer<typeof AddressesUpdateSchema>;
