// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const AerialInspectionsBaseRowSchema = z.object({
	aerial_site_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	density_id: z.uuid().nullable(),
	dips_count: z.number().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	inspected_by: z.uuid(),
	inspection_date: z.coerce.date<Date>(),
	is_wet: z.boolean(),
	larvae_count: z.number().nullable(),
	larvae_per_dip: z.number().nullable(),
	notes: z.string().nullable(),
	result: z.enum(['recheck', 'fly', 'hand treat', 'no action']),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type AerialInspectionsBaseRow = z.infer<typeof AerialInspectionsBaseRowSchema>;

export const AerialInspectionsInsertSchema = z.object({
	aerial_site_id: z.uuid(),
	density_id: z.uuid().nullable(),
	dips_count: z.number().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	inspected_by: z.uuid(),
	inspection_date: z.coerce.date<Date>(),
	is_wet: z.boolean(),
	larvae_count: z.number().nullable(),
	larvae_per_dip: z.number().nullable(),
	notes: z.string().nullable(),
	result: z.enum(['recheck', 'fly', 'hand treat', 'no action']),
});

export type AerialInspectionsInsert = z.infer<typeof AerialInspectionsInsertSchema>;

export const AerialInspectionsUpdateSchema = AerialInspectionsInsertSchema.omit({ id: true }).partial();

export type AerialInspectionsUpdate = z.infer<typeof AerialInspectionsUpdateSchema>;
