// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const AerialSitesBaseRowSchema = z.object({
	aerial_site_code: z.string().nullable(),
	aerial_site_name: z.string(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_active: z.boolean(),
	metadata: z.record(z.unknown()).nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type AerialSitesBaseRow = z.infer<typeof AerialSitesBaseRowSchema>;

export const AerialSitesInsertSchema = z.object({
	aerial_site_code: z.string().nullable(),
	aerial_site_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_active: z.boolean(),
	metadata: z.record(z.unknown()).nullable(),
});

export type AerialSitesInsert = z.infer<typeof AerialSitesInsertSchema>;

export const AerialSitesUpdateSchema = AerialSitesInsertSchema.omit({ id: true }).partial();

export type AerialSitesUpdate = z.infer<typeof AerialSitesUpdateSchema>;
