// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const CatchBasinMissionsBaseRowSchema = z.object({
	basin_count: z.number(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	notes: z.string().nullable(),
	sample_dry: z.number().nullable(),
	sample_wet: z.number().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type CatchBasinMissionsBaseRow = z.infer<typeof CatchBasinMissionsBaseRowSchema>;

export const CatchBasinMissionsInsertSchema = z.object({
	basin_count: z.number(),
	group_id: z.uuid(),
	id: z.uuid(),
	notes: z.string().nullable(),
	sample_dry: z.number().nullable(),
	sample_wet: z.number().nullable(),
});

export type CatchBasinMissionsInsert = z.infer<typeof CatchBasinMissionsInsertSchema>;

export const CatchBasinMissionsUpdateSchema = CatchBasinMissionsInsertSchema.omit({ id: true }).partial();

export type CatchBasinMissionsUpdate = z.infer<typeof CatchBasinMissionsUpdateSchema>;
