// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const CollectionsBaseRowSchema = z.object({
	collected_by: z.uuid().nullable(),
	collection_date: z.coerce.date<Date>().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	has_error: z.boolean().nullable(),
	id: z.uuid(),
	trap_id: z.uuid(),
	trap_lure_id: z.uuid().nullable(),
	trap_nights: z.number().nullable(),
	trap_set_by: z.uuid().nullable(),
	trap_set_date: z.coerce.date<Date>().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type CollectionsBaseRow = z.infer<typeof CollectionsBaseRowSchema>;

export const CollectionsInsertSchema = z.object({
	collected_by: z.uuid().nullable(),
	collection_date: z.coerce.date<Date>().nullable(),
	group_id: z.uuid(),
	has_error: z.boolean().nullable(),
	id: z.uuid(),
	trap_id: z.uuid(),
	trap_lure_id: z.uuid().nullable(),
	trap_nights: z.number().nullable(),
	trap_set_by: z.uuid().nullable(),
	trap_set_date: z.coerce.date<Date>().nullable(),
});

export type CollectionsInsert = z.infer<typeof CollectionsInsertSchema>;

export const CollectionsUpdateSchema = CollectionsInsertSchema.omit({ id: true }).partial();

export type CollectionsUpdate = z.infer<typeof CollectionsUpdateSchema>;
