// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const CommentsBaseRowSchema = z.object({
	aerial_site_id: z.uuid().nullable(),
	collection_id: z.uuid().nullable(),
	comment_text: z.string(),
	contact_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_pinned: z.boolean(),
	landing_rate_id: z.uuid().nullable(),
	notification_id: z.uuid().nullable(),
	parent_id: z.uuid().nullable(),
	parent_type: z.string().nullable(),
	sample_id: z.uuid().nullable(),
	service_request_id: z.uuid().nullable(),
	trap_id: z.uuid().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type CommentsBaseRow = z.infer<typeof CommentsBaseRowSchema>;

export const CommentsInsertSchema = z.object({
	aerial_site_id: z.uuid().nullable(),
	collection_id: z.uuid().nullable(),
	comment_text: z.string(),
	contact_id: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_pinned: z.boolean(),
	landing_rate_id: z.uuid().nullable(),
	notification_id: z.uuid().nullable(),
	parent_id: z.uuid().nullable(),
	parent_type: z.string().nullable(),
	sample_id: z.uuid().nullable(),
	service_request_id: z.uuid().nullable(),
	trap_id: z.uuid().nullable(),
});

export type CommentsInsert = z.infer<typeof CommentsInsertSchema>;

export const CommentsUpdateSchema = CommentsInsertSchema.omit({ id: true }).partial();

export type CommentsUpdate = z.infer<typeof CommentsUpdateSchema>;
