// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const FlightAerialSitesBaseRowSchema = z.object({
	aerial_site_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	flight_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type FlightAerialSitesBaseRow = z.infer<typeof FlightAerialSitesBaseRowSchema>;

export const FlightAerialSitesInsertSchema = z.object({
	aerial_site_id: z.uuid(),
	flight_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
});

export type FlightAerialSitesInsert = z.infer<typeof FlightAerialSitesInsertSchema>;

export const FlightAerialSitesUpdateSchema = FlightAerialSitesInsertSchema.omit({ id: true }).partial();

export type FlightAerialSitesUpdate = z.infer<typeof FlightAerialSitesUpdateSchema>;
