// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const FlightBatchesBaseRowSchema = z.object({
	batch_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	flight_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type FlightBatchesBaseRow = z.infer<typeof FlightBatchesBaseRowSchema>;

export const FlightBatchesInsertSchema = z.object({
	batch_id: z.uuid(),
	flight_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
});

export type FlightBatchesInsert = z.infer<typeof FlightBatchesInsertSchema>;

export const FlightBatchesUpdateSchema = FlightBatchesInsertSchema.omit({ id: true }).partial();

export type FlightBatchesUpdate = z.infer<typeof FlightBatchesUpdateSchema>;
