// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const FlightsBaseRowSchema = z.object({
	aircraft_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	flight_by: z.uuid(),
	flight_date: z.coerce.date<Date>(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.record(z.unknown()).nullable(),
	notes: z.string().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type FlightsBaseRow = z.infer<typeof FlightsBaseRowSchema>;

export const FlightsInsertSchema = z.object({
	aircraft_id: z.uuid(),
	flight_by: z.uuid(),
	flight_date: z.coerce.date<Date>(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.record(z.unknown()).nullable(),
	notes: z.string().nullable(),
});

export type FlightsInsert = z.infer<typeof FlightsInsertSchema>;

export const FlightsUpdateSchema = FlightsInsertSchema.omit({ id: true }).partial();

export type FlightsUpdate = z.infer<typeof FlightsUpdateSchema>;
