// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const HabitatsBaseRowSchema = z.object({
	address_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	description: z.string(),
	group_id: z.uuid(),
	habitat_name: z.string().nullable(),
	id: z.uuid(),
	is_active: z.boolean(),
	is_inaccessible: z.boolean(),
	is_permanent: z.boolean(),
	lat: z.number(),
	lng: z.number(),
	metadata: z.record(z.unknown()).nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type HabitatsBaseRow = z.infer<typeof HabitatsBaseRowSchema>;

export const HabitatsInsertSchema = z.object({
	address_id: z.uuid().nullable(),
	description: z.string(),
	group_id: z.uuid(),
	habitat_name: z.string().nullable(),
	id: z.uuid(),
	is_active: z.boolean(),
	is_inaccessible: z.boolean(),
	is_permanent: z.boolean(),
	lat: z.number(),
	lng: z.number(),
	metadata: z.record(z.unknown()).nullable(),
});

export type HabitatsInsert = z.infer<typeof HabitatsInsertSchema>;

export const HabitatsUpdateSchema = HabitatsInsertSchema.omit({ id: true }).partial();

export type HabitatsUpdate = z.infer<typeof HabitatsUpdateSchema>;
