// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const HandUlvsBaseRowSchema = z.object({
	address_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	end_temperature: z.number().nullable(),
	end_time: z.coerce.date<Date>().nullable(),
	end_wind_speed: z.number().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	lat: z.number().nullable(),
	lng: z.number().nullable(),
	notes: z.string().nullable(),
	start_temperature: z.number().nullable(),
	start_time: z.coerce.date<Date>().nullable(),
	start_wind_speed: z.number().nullable(),
	temperature_unit_id: z.uuid().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
	wind_speed_unit_id: z.uuid().nullable(),
});

export type HandUlvsBaseRow = z.infer<typeof HandUlvsBaseRowSchema>;

export const HandUlvsInsertSchema = z.object({
	address_id: z.uuid().nullable(),
	end_temperature: z.number().nullable(),
	end_time: z.coerce.date<Date>().nullable(),
	end_wind_speed: z.number().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	lat: z.number().nullable(),
	lng: z.number().nullable(),
	notes: z.string().nullable(),
	start_temperature: z.number().nullable(),
	start_time: z.coerce.date<Date>().nullable(),
	start_wind_speed: z.number().nullable(),
	temperature_unit_id: z.uuid().nullable(),
	wind_speed_unit_id: z.uuid().nullable(),
});

export type HandUlvsInsert = z.infer<typeof HandUlvsInsertSchema>;

export const HandUlvsUpdateSchema = HandUlvsInsertSchema.omit({ id: true }).partial();

export type HandUlvsUpdate = z.infer<typeof HandUlvsUpdateSchema>;
