// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const InsecticidesBaseRowSchema = z.object({
	active_ingredient: z.string(),
	conversion_factor: z.number().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	default_unit_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
	label_url: z.string().nullable(),
	metadata: z.record(z.unknown()).nullable(),
	msds_url: z.string().nullable(),
	registration_number: z.string(),
	shorthand: z.string().nullable(),
	trade_name: z.string(),
	type: z.enum(['larvicide', 'adulticide', 'pupicide', 'other']),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type InsecticidesBaseRow = z.infer<typeof InsecticidesBaseRowSchema>;

export const InsecticidesInsertSchema = z.object({
	active_ingredient: z.string(),
	conversion_factor: z.number().nullable(),
	default_unit_id: z.uuid(),
	group_id: z.uuid(),
	id: z.uuid(),
	label_url: z.string().nullable(),
	metadata: z.record(z.unknown()).nullable(),
	msds_url: z.string().nullable(),
	registration_number: z.string(),
	shorthand: z.string().nullable(),
	trade_name: z.string(),
	type: z.enum(['larvicide', 'adulticide', 'pupicide', 'other']),
});

export type InsecticidesInsert = z.infer<typeof InsecticidesInsertSchema>;

export const InsecticidesUpdateSchema = InsecticidesInsertSchema.omit({ id: true }).partial();

export type InsecticidesUpdate = z.infer<typeof InsecticidesUpdateSchema>;
