// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const InspectionsBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	density_id: z.uuid().nullable(),
	dip_count: z.number().nullable(),
	group_id: z.uuid(),
	habitat_id: z.uuid(),
	has_eggs: z.boolean(),
	has_first_instar: z.boolean(),
	has_fourth_instar: z.boolean(),
	has_pupae: z.boolean(),
	has_second_instar: z.boolean(),
	has_third_instar: z.boolean(),
	id: z.uuid(),
	inspected_by: z.uuid().nullable(),
	inspection_date: z.coerce.date<Date>(),
	is_source_reduction: z.boolean(),
	is_wet: z.boolean(),
	larvae_count: z.number().nullable(),
	notes: z.string().nullable(),
	source_reduction_notes: z.string().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type InspectionsBaseRow = z.infer<typeof InspectionsBaseRowSchema>;

export const InspectionsInsertSchema = z.object({
	density_id: z.uuid().nullable(),
	dip_count: z.number().nullable(),
	group_id: z.uuid(),
	habitat_id: z.uuid(),
	has_eggs: z.boolean(),
	has_first_instar: z.boolean(),
	has_fourth_instar: z.boolean(),
	has_pupae: z.boolean(),
	has_second_instar: z.boolean(),
	has_third_instar: z.boolean(),
	id: z.uuid(),
	inspected_by: z.uuid().nullable(),
	inspection_date: z.coerce.date<Date>(),
	is_source_reduction: z.boolean(),
	is_wet: z.boolean(),
	larvae_count: z.number().nullable(),
	notes: z.string().nullable(),
	source_reduction_notes: z.string().nullable(),
});

export type InspectionsInsert = z.infer<typeof InspectionsInsertSchema>;

export const InspectionsUpdateSchema = InspectionsInsertSchema.omit({ id: true }).partial();

export type InspectionsUpdate = z.infer<typeof InspectionsUpdateSchema>;
