// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const LandingRatesBaseRowSchema = z.object({
	address_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	duration_amount: z.number().nullable(),
	duration_unit_id: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	landing_rate_by: z.uuid().nullable(),
	landing_rate_date: z.coerce.date<Date>(),
	lat: z.number(),
	lng: z.number(),
	observed_count: z.number(),
	sample_id: z.uuid().nullable(),
	started_at: z.coerce.date<Date>().nullable(),
	stopped_at: z.coerce.date<Date>().nullable(),
	temperature: z.number().nullable(),
	temperature_unit_id: z.uuid().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
	wind_speed: z.number().nullable(),
	wind_speed_unit_id: z.uuid().nullable(),
});

export type LandingRatesBaseRow = z.infer<typeof LandingRatesBaseRowSchema>;

export const LandingRatesInsertSchema = z.object({
	address_id: z.uuid().nullable(),
	duration_amount: z.number().nullable(),
	duration_unit_id: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	landing_rate_by: z.uuid().nullable(),
	landing_rate_date: z.coerce.date<Date>(),
	lat: z.number(),
	lng: z.number(),
	observed_count: z.number(),
	sample_id: z.uuid().nullable(),
	started_at: z.coerce.date<Date>().nullable(),
	stopped_at: z.coerce.date<Date>().nullable(),
	temperature: z.number().nullable(),
	temperature_unit_id: z.uuid().nullable(),
	wind_speed: z.number().nullable(),
	wind_speed_unit_id: z.uuid().nullable(),
});

export type LandingRatesInsert = z.infer<typeof LandingRatesInsertSchema>;

export const LandingRatesUpdateSchema = LandingRatesInsertSchema.omit({ id: true }).partial();

export type LandingRatesUpdate = z.infer<typeof LandingRatesUpdateSchema>;
