// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const ProfilesBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	full_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.unknown().nullable(),
	role_id: z.uuid().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
	user_id: z.uuid(),
});

export type ProfilesBaseRow = z.infer<typeof ProfilesBaseRowSchema>;

export const ProfilesInsertSchema = z.object({
	full_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.unknown().nullable(),
	role_id: z.uuid().nullable(),
	user_id: z.uuid(),
});

export type ProfilesInsert = z.infer<typeof ProfilesInsertSchema>;

export const ProfilesUpdateSchema = ProfilesInsertSchema.omit({ id: true }).partial();

export type ProfilesUpdate = z.infer<typeof ProfilesUpdateSchema>;
