// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const RegionsBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid().nullable(),
	id: z.uuid(),
	metadata: z.record(z.unknown()).nullable(),
	name_path: z.string().nullable(),
	parent_id: z.uuid().nullable(),
	region_folder_id: z.uuid().nullable(),
	region_name: z.string(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type RegionsBaseRow = z.infer<typeof RegionsBaseRowSchema>;

export const RegionsInsertSchema = z.object({
	group_id: z.uuid().nullable(),
	id: z.uuid(),
	metadata: z.record(z.unknown()).nullable(),
	name_path: z.string().nullable(),
	parent_id: z.uuid().nullable(),
	region_folder_id: z.uuid().nullable(),
	region_name: z.string(),
});

export type RegionsInsert = z.infer<typeof RegionsInsertSchema>;

export const RegionsUpdateSchema = RegionsInsertSchema.omit({ id: true }).partial();

export type RegionsUpdate = z.infer<typeof RegionsUpdateSchema>;
