// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const RoutesBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	route_name: z.string(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type RoutesBaseRow = z.infer<typeof RoutesBaseRowSchema>;

export const RoutesInsertSchema = z.object({
	group_id: z.uuid(),
	id: z.uuid(),
	route_name: z.string(),
});

export type RoutesInsert = z.infer<typeof RoutesInsertSchema>;

export const RoutesUpdateSchema = RoutesInsertSchema.omit({ id: true }).partial();

export type RoutesUpdate = z.infer<typeof RoutesUpdateSchema>;
