// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const SamplesBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	display_name: z.string().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	inspection_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type SamplesBaseRow = z.infer<typeof SamplesBaseRowSchema>;

export const SamplesInsertSchema = z.object({
	display_name: z.string().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	inspection_id: z.uuid(),
});

export type SamplesInsert = z.infer<typeof SamplesInsertSchema>;

export const SamplesUpdateSchema = SamplesInsertSchema.omit({ id: true }).partial();

export type SamplesUpdate = z.infer<typeof SamplesUpdateSchema>;
