// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const ServiceRequestsBaseRowSchema = z.object({
	address_id: z.uuid(),
	contact_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	details: z.string(),
	display_number: z.number(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_closed: z.boolean(),
	request_date: z.coerce.date<Date>(),
	source: z.enum(['online', 'phone', 'walk-in', 'other']).nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type ServiceRequestsBaseRow = z.infer<typeof ServiceRequestsBaseRowSchema>;

export const ServiceRequestsInsertSchema = z.object({
	address_id: z.uuid(),
	contact_id: z.uuid(),
	details: z.string(),
	display_number: z.number(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_closed: z.boolean(),
	request_date: z.coerce.date<Date>(),
	source: z.enum(['online', 'phone', 'walk-in', 'other']).nullable(),
});

export type ServiceRequestsInsert = z.infer<typeof ServiceRequestsInsertSchema>;

export const ServiceRequestsUpdateSchema = ServiceRequestsInsertSchema.omit({ id: true }).partial();

export type ServiceRequestsUpdate = z.infer<typeof ServiceRequestsUpdateSchema>;
