// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const ServiceRequestTagsBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	service_request_id: z.uuid(),
	tag_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type ServiceRequestTagsBaseRow = z.infer<typeof ServiceRequestTagsBaseRowSchema>;

export const ServiceRequestTagsInsertSchema = z.object({
	group_id: z.uuid(),
	id: z.uuid(),
	service_request_id: z.uuid(),
	tag_id: z.uuid(),
});

export type ServiceRequestTagsInsert = z.infer<typeof ServiceRequestTagsInsertSchema>;

export const ServiceRequestTagsUpdateSchema = ServiceRequestTagsInsertSchema.omit({ id: true }).partial();

export type ServiceRequestTagsUpdate = z.infer<typeof ServiceRequestTagsUpdateSchema>;
