// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const TagsBaseRowSchema = z.object({
	color: z.string().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	tag_group_id: z.uuid(),
	tag_name: z.string(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type TagsBaseRow = z.infer<typeof TagsBaseRowSchema>;

export const TagsInsertSchema = z.object({
	color: z.string().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	tag_group_id: z.uuid(),
	tag_name: z.string(),
});

export type TagsInsert = z.infer<typeof TagsInsertSchema>;

export const TagsUpdateSchema = TagsInsertSchema.omit({ id: true }).partial();

export type TagsUpdate = z.infer<typeof TagsUpdateSchema>;
