// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const TrapsBaseRowSchema = z.object({
	address_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_active: z.boolean(),
	is_permanent: z.boolean(),
	lat: z.number(),
	lng: z.number(),
	metadata: z.record(z.unknown()).nullable(),
	trap_code: z.string().nullable(),
	trap_name: z.string().nullable(),
	trap_type_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type TrapsBaseRow = z.infer<typeof TrapsBaseRowSchema>;

export const TrapsInsertSchema = z.object({
	address_id: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_active: z.boolean(),
	is_permanent: z.boolean(),
	lat: z.number(),
	lng: z.number(),
	metadata: z.record(z.unknown()).nullable(),
	trap_code: z.string().nullable(),
	trap_name: z.string().nullable(),
	trap_type_id: z.uuid(),
});

export type TrapsInsert = z.infer<typeof TrapsInsertSchema>;

export const TrapsUpdateSchema = TrapsInsertSchema.omit({ id: true }).partial();

export type TrapsUpdate = z.infer<typeof TrapsUpdateSchema>;
