// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const TrapTagsBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	tag_id: z.uuid(),
	trap_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type TrapTagsBaseRow = z.infer<typeof TrapTagsBaseRowSchema>;

export const TrapTagsInsertSchema = z.object({
	group_id: z.uuid(),
	id: z.uuid(),
	tag_id: z.uuid(),
	trap_id: z.uuid(),
});

export type TrapTagsInsert = z.infer<typeof TrapTagsInsertSchema>;

export const TrapTagsUpdateSchema = TrapTagsInsertSchema.omit({ id: true }).partial();

export type TrapTagsUpdate = z.infer<typeof TrapTagsUpdateSchema>;
