// Auto-generated by create-types-files.ts — 2026-02-13T00:41:02.350Z
// Do not edit manually.

import z from 'zod';

export const TrapLuresBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid().nullable(),
	id: z.uuid(),
	lure_name: z.string(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type TrapLuresBaseRow = z.infer<typeof TrapLuresBaseRowSchema>;

export const TrapLuresInsertSchema = z.object({
	group_id: z.uuid().nullable(),
	id: z.uuid(),
	lure_name: z.string(),
});

export type TrapLuresInsert = z.infer<typeof TrapLuresInsertSchema>;

export const TrapLuresUpdateSchema = TrapLuresInsertSchema.omit({ id: true }).partial();

export type TrapLuresUpdate = z.infer<typeof TrapLuresUpdateSchema>;
