// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const UlvMissionsBaseRowSchema = z.object({
	area_description: z.string().nullable(),
	completion_date: z.coerce.date<Date>().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	end_time: z.coerce.date<Date>().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_cancelled: z.boolean(),
	mission_date: z.coerce.date<Date>(),
	rain_date: z.coerce.date<Date>().nullable(),
	start_time: z.coerce.date<Date>().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type UlvMissionsBaseRow = z.infer<typeof UlvMissionsBaseRowSchema>;

export const UlvMissionsInsertSchema = z.object({
	area_description: z.string().nullable(),
	completion_date: z.coerce.date<Date>().nullable(),
	end_time: z.coerce.date<Date>().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	is_cancelled: z.boolean(),
	mission_date: z.coerce.date<Date>(),
	rain_date: z.coerce.date<Date>().nullable(),
	start_time: z.coerce.date<Date>().nullable(),
});

export type UlvMissionsInsert = z.infer<typeof UlvMissionsInsertSchema>;

export const UlvMissionsUpdateSchema = UlvMissionsInsertSchema.omit({ id: true }).partial();

export type UlvMissionsUpdate = z.infer<typeof UlvMissionsUpdateSchema>;
