// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const VehiclesBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.unknown().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
	vehicle_name: z.string(),
});

export type VehiclesBaseRow = z.infer<typeof VehiclesBaseRowSchema>;

export const VehiclesInsertSchema = z.object({
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.unknown().nullable(),
	vehicle_name: z.string(),
});

export type VehiclesInsert = z.infer<typeof VehiclesInsertSchema>;

export const VehiclesUpdateSchema = VehiclesInsertSchema.omit({ id: true }).partial();

export type VehiclesUpdate = z.infer<typeof VehiclesUpdateSchema>;
