import { createSyncDescriptor } from '../descriptor-factory.js';
import type { AdultCollectionRow } from '../index.js';

export const collectionsSyncDescriptor = createSyncDescriptor<AdultCollectionRow>({
	id: 'collections',
	table: 'collections',
	endpointPath: '/sync/shapes/collections',
	columns: [
		'id',
		'organizationId',
		'lat',
		'lng',
		'geomType',
		'trapId',
		'collectionMethodId',
		'collectionLureId',
		'addressId',
		'collectedAt',
		'collectedByProfileId',
		'startedAt',
		'setByProfileId',
		'setAssignmentItemId',
		'collectedAssignmentItemId',
		'collectionTimingMode',
		'collectionDate',
		'durationAmount',
		'durationUnitId',
		'hasProblem',
		'isZeroResult',
		'hasBycatch',
		'metadata',
		'createdByProfileId',
		'updatedByProfileId',
		'createdAt',
		'updatedAt',
	],
	getKey: (row) => row.id,
});
