import { createSyncDescriptor } from '../descriptor-factory.js';
import type { InspectionRow } from '../index.js';

export const inspectionsSyncDescriptor = createSyncDescriptor<InspectionRow>({
	id: 'inspections',
	table: 'inspections',
	endpointPath: '/sync/shapes/inspections',
	syncMode: 'on-demand',
	columns: [
		'id',
		'organizationId',
		'lat',
		'lng',
		'geomType',
		'habitatId',
		'habitatTypeId',
		'addressId',
		'inspectedByProfileId',
		'assignmentItemId',
		'inspectionDate',
		'isWet',
		'dipCount',
		'density',
		'larvaeCount',
		'hasFirstInstar',
		'hasSecondInstar',
		'hasThirdInstar',
		'hasFourthInstar',
		'hasPupae',
		'hasEggs',
		'createdByProfileId',
		'updatedByProfileId',
		'createdAt',
		'updatedAt',
	],
	getKey: (row) => row.id,
});
