import type { Hono } from 'hono';
import type { AuthVariables } from '../auth-middleware.js';
import { registerContactRoutes } from './contacts.js';
import { registerMissionNotificationRoutes } from './mission-notifications.js';
import { registerNotificationRegistrationTypeRoutes } from './notification-registration-types.js';
import { registerNotificationRegistrationRoutes } from './notification-registrations.js';
import { registerServiceRequestRoutes } from './service-requests.js';
import type { RouteOptions } from './shared.js';

/**
 * Public engagement command endpoints: contacts, service requests, notification
 * registrations (+ registration-type subscriptions), and mission-notification
 * status transitions. (Notification *types* are handled separately in
 * public-engagement-commands.ts.)
 *
 * Service requests and notification registrations accept either an existing
 * contact/address reference or an inline `{ kind: 'new', ... }` payload that the
 * server materializes first. Mission notifications are generated by an automated
 * server-side flow (not wired here); only their status transitions are exposed.
 */
export function registerPublicEngagementRecordRoutes(
	app: Hono<{ Variables: AuthVariables }>,
	options: RouteOptions,
): void {
	registerContactRoutes(app, options);
	registerServiceRequestRoutes(app, options);
	registerNotificationRegistrationRoutes(app, options);
	registerNotificationRegistrationTypeRoutes(app, options);
	registerMissionNotificationRoutes(app, options);
}
