/**
 * Every table's schema, reachable by table name.
 *
 * The server registers a shape route per table and has to force that route's
 * column list upstream. Those columns are `Object.keys` of the schema, so this
 * is what lets it read them without a second list to keep in step — the schema
 * decides both what a client parses and what the shape is allowed to carry.
 *
 * Keyed by the Postgres table name rather than exported one by one, because the
 * server iterates rather than naming tables.
 *
 * Generated by `pnpm generate:schemas`.
 */

import { additionalPersonnelSchema } from './additional_personnel.js';
import { addressSchema } from './addresses.js';
import { applicationBatchSchema } from './application_batches.js';
import { applicationMethodSchema } from './application_methods.js';
import { applicationSchema } from './applications.js';
import { assignmentItemSchema } from './assignment_items.js';
import { assignmentSchema } from './assignments.js';
import { biocontrolActionSchema } from './biocontrol_actions.js';
import { biocontrolMethodSchema } from './biocontrol_methods.js';
import { collectionLureSchema } from './collection_lures.js';
import { collectionMethodSchema } from './collection_methods.js';
import { collectionSpeciesSchema } from './collection_species.js';
import { collectionSchema } from './collections.js';
import { commentSchema } from './comments.js';
import { contactSchema } from './contacts.js';
import { equipmentSchema } from './equipment.js';
import { formulationInsecticideSchema } from './formulation_insecticides.js';
import { formulationSchema } from './formulations.js';
import { genusSchema } from './genera.js';
import { habitatTypeSchema } from './habitat_types.js';
import { habitatSchema } from './habitats.js';
import { insecticideBatchSchema } from './insecticide_batches.js';
import { insecticideSchema } from './insecticides.js';
import { inspectionSchema } from './inspections.js';
import { membershipSchema } from './memberships.js';
import { missionItemSchema } from './mission_items.js';
import { missionNotificationSchema } from './mission_notifications.js';
import { missionSchema } from './missions.js';
import { notificationRegistrationTypeSchema } from './notification_registration_types.js';
import { notificationRegistrationSchema } from './notification_registrations.js';
import { notificationTypeSchema } from './notification_types.js';
import { organizationSpeciesSchema } from './organization_species.js';
import { organizationSchema } from './organizations.js';
import { outreachActionSchema } from './outreach_actions.js';
import { outreachMethodSchema } from './outreach_methods.js';
import { profileSchema } from './profiles.js';
import { regionFolderSchema } from './region_folders.js';
import { regionSchema } from './regions.js';
import { requestedControlActionSchema } from './requested_control_actions.js';
import { routeItemSchema } from './route_items.js';
import { routeSchema } from './routes.js';
import { sampleSpeciesSchema } from './sample_species.js';
import { sampleSchema } from './samples.js';
import { serviceRequestSchema } from './service_requests.js';
import { sourceReductionMethodSchema } from './source_reduction_methods.js';
import { sourceReductionSchema } from './source_reductions.js';
import { speciesSchema } from './species.js';
import { tagItemSchema } from './tag_items.js';
import { tagSchema } from './tags.js';
import { trapSchema } from './traps.js';
import { unitSchema } from './units.js';
import { userSchema } from './users.js';
import { vehicleSchema } from './vehicles.js';
import { weatherSourceSubscriptionSchema } from './weather_source_subscriptions.js';
import { weatherSourceSchema } from './weather_sources.js';
import { weatherSummarySchema } from './weather_summaries.js';

export const tableSchemas = {
	additional_personnel: additionalPersonnelSchema,
	addresses: addressSchema,
	application_batches: applicationBatchSchema,
	application_methods: applicationMethodSchema,
	applications: applicationSchema,
	assignment_items: assignmentItemSchema,
	assignments: assignmentSchema,
	biocontrol_actions: biocontrolActionSchema,
	biocontrol_methods: biocontrolMethodSchema,
	collection_lures: collectionLureSchema,
	collection_methods: collectionMethodSchema,
	collection_species: collectionSpeciesSchema,
	collections: collectionSchema,
	comments: commentSchema,
	contacts: contactSchema,
	equipment: equipmentSchema,
	formulation_insecticides: formulationInsecticideSchema,
	formulations: formulationSchema,
	genera: genusSchema,
	habitat_types: habitatTypeSchema,
	habitats: habitatSchema,
	insecticide_batches: insecticideBatchSchema,
	insecticides: insecticideSchema,
	inspections: inspectionSchema,
	memberships: membershipSchema,
	mission_items: missionItemSchema,
	mission_notifications: missionNotificationSchema,
	missions: missionSchema,
	notification_registration_types: notificationRegistrationTypeSchema,
	notification_registrations: notificationRegistrationSchema,
	notification_types: notificationTypeSchema,
	organization_species: organizationSpeciesSchema,
	organizations: organizationSchema,
	outreach_actions: outreachActionSchema,
	outreach_methods: outreachMethodSchema,
	profiles: profileSchema,
	region_folders: regionFolderSchema,
	regions: regionSchema,
	requested_control_actions: requestedControlActionSchema,
	route_items: routeItemSchema,
	routes: routeSchema,
	sample_species: sampleSpeciesSchema,
	samples: sampleSchema,
	service_requests: serviceRequestSchema,
	source_reduction_methods: sourceReductionMethodSchema,
	source_reductions: sourceReductionSchema,
	species: speciesSchema,
	tag_items: tagItemSchema,
	tags: tagSchema,
	traps: trapSchema,
	units: unitSchema,
	users: userSchema,
	vehicles: vehicleSchema,
	weather_source_subscriptions: weatherSourceSubscriptionSchema,
	weather_sources: weatherSourceSchema,
	weather_summaries: weatherSummarySchema,
} as const;

/** A table with a collection. Every key of {@link tableSchemas}. */
export type SyncedTable = keyof typeof tableSchemas;
