// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const ApplicationsBaseRowSchema = z.object({
	amount_applied: z.number(),
	application_date: z.coerce.date<Date>(),
	application_unit_id: z.uuid(),
	applicator_id: z.uuid(),
	batch_id: z.uuid().nullable(),
	catch_basin_mission_id: z.uuid().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	flight_aerial_site_id: z.uuid().nullable(),
	group_id: z.uuid(),
	hand_ulv_id: z.uuid().nullable(),
	id: z.uuid(),
	insecticide_id: z.uuid(),
	inspection_id: z.uuid().nullable(),
	truck_ulv_id: z.uuid().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type ApplicationsBaseRow = z.infer<typeof ApplicationsBaseRowSchema>;

export const ApplicationsInsertSchema = z.object({
	amount_applied: z.number(),
	application_date: z.coerce.date<Date>(),
	application_unit_id: z.uuid(),
	applicator_id: z.uuid(),
	batch_id: z.uuid().nullable(),
	catch_basin_mission_id: z.uuid().nullable(),
	flight_aerial_site_id: z.uuid().nullable(),
	group_id: z.uuid(),
	hand_ulv_id: z.uuid().nullable(),
	id: z.uuid(),
	insecticide_id: z.uuid(),
	inspection_id: z.uuid().nullable(),
	truck_ulv_id: z.uuid().nullable(),
});

export type ApplicationsInsert = z.infer<typeof ApplicationsInsertSchema>;

export const ApplicationsUpdateSchema = ApplicationsInsertSchema.omit({ id: true }).partial();

export type ApplicationsUpdate = z.infer<typeof ApplicationsUpdateSchema>;
