// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const ContactsBaseRowSchema = z.object({
	alternate_phone: z.string().nullable(),
	contact_name: z.string().nullable(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	department: z.string().nullable(),
	email: z.string().nullable(),
	fax: z.string().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.unknown().nullable(),
	organization: z.string().nullable(),
	preferred_phone: z.string().nullable(),
	title: z.string().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type ContactsBaseRow = z.infer<typeof ContactsBaseRowSchema>;

export const ContactsInsertSchema = z.object({
	alternate_phone: z.string().nullable(),
	contact_name: z.string().nullable(),
	department: z.string().nullable(),
	email: z.string().nullable(),
	fax: z.string().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	metadata: z.unknown().nullable(),
	organization: z.string().nullable(),
	preferred_phone: z.string().nullable(),
	title: z.string().nullable(),
});

export type ContactsInsert = z.infer<typeof ContactsInsertSchema>;

export const ContactsUpdateSchema = ContactsInsertSchema.omit({ id: true }).partial();

export type ContactsUpdate = z.infer<typeof ContactsUpdateSchema>;
