// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const DensitiesBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	density_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	range_max: z.number().nullable(),
	range_min: z.number().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type DensitiesBaseRow = z.infer<typeof DensitiesBaseRowSchema>;

export const DensitiesInsertSchema = z.object({
	density_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	range_max: z.number().nullable(),
	range_min: z.number().nullable(),
});

export type DensitiesInsert = z.infer<typeof DensitiesInsertSchema>;

export const DensitiesUpdateSchema = DensitiesInsertSchema.omit({ id: true }).partial();

export type DensitiesUpdate = z.infer<typeof DensitiesUpdateSchema>;
