// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const HabitatTagsBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	habitat_id: z.uuid(),
	id: z.uuid(),
	tag_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type HabitatTagsBaseRow = z.infer<typeof HabitatTagsBaseRowSchema>;

export const HabitatTagsInsertSchema = z.object({
	group_id: z.uuid(),
	habitat_id: z.uuid(),
	id: z.uuid(),
	tag_id: z.uuid(),
});

export type HabitatTagsInsert = z.infer<typeof HabitatTagsInsertSchema>;

export const HabitatTagsUpdateSchema = HabitatTagsInsertSchema.omit({ id: true }).partial();

export type HabitatTagsUpdate = z.infer<typeof HabitatTagsUpdateSchema>;
