// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const InsecticideBatchesBaseRowSchema = z.object({
	batch_name: z.string(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	id: z.uuid(),
	insecticide_id: z.uuid(),
	is_active: z.boolean(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type InsecticideBatchesBaseRow = z.infer<typeof InsecticideBatchesBaseRowSchema>;

export const InsecticideBatchesInsertSchema = z.object({
	batch_name: z.string(),
	group_id: z.uuid(),
	id: z.uuid(),
	insecticide_id: z.uuid(),
	is_active: z.boolean(),
});

export type InsecticideBatchesInsert = z.infer<typeof InsecticideBatchesInsertSchema>;

export const InsecticideBatchesUpdateSchema = InsecticideBatchesInsertSchema.omit({ id: true }).partial();

export type InsecticideBatchesUpdate = z.infer<typeof InsecticideBatchesUpdateSchema>;
