// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const NotificationsBaseRowSchema = z.object({
	address_id: z.uuid(),
	contact_id: z.uuid(),
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	has_bees: z.boolean(),
	id: z.uuid(),
	is_active: z.boolean(),
	is_no_spray: z.boolean(),
	radius: z.number().nullable(),
	radius_unit_id: z.uuid().nullable(),
	region_id: z.uuid().nullable(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
	wants_email: z.boolean(),
	wants_fax: z.boolean(),
	wants_phone: z.boolean(),
});

export type NotificationsBaseRow = z.infer<typeof NotificationsBaseRowSchema>;

export const NotificationsInsertSchema = z.object({
	address_id: z.uuid(),
	contact_id: z.uuid(),
	group_id: z.uuid(),
	has_bees: z.boolean(),
	id: z.uuid(),
	is_active: z.boolean(),
	is_no_spray: z.boolean(),
	radius: z.number().nullable(),
	radius_unit_id: z.uuid().nullable(),
	region_id: z.uuid().nullable(),
	wants_email: z.boolean(),
	wants_fax: z.boolean(),
	wants_phone: z.boolean(),
});

export type NotificationsInsert = z.infer<typeof NotificationsInsertSchema>;

export const NotificationsUpdateSchema = NotificationsInsertSchema.omit({ id: true }).partial();

export type NotificationsUpdate = z.infer<typeof NotificationsUpdateSchema>;
