// Auto-generated by create-types-files.ts — 2026-02-12T01:22:13.173Z
// Do not edit manually.

import z from 'zod';

export const RouteItemsBaseRowSchema = z.object({
	created_at: z.coerce.date<Date>(),
	created_by: z.uuid().nullable(),
	group_id: z.uuid(),
	habitat_id: z.uuid().nullable(),
	id: z.uuid(),
	rank_string: z.string(),
	route_id: z.uuid(),
	updated_at: z.coerce.date<Date>(),
	updated_by: z.uuid().nullable(),
});

export type RouteItemsBaseRow = z.infer<typeof RouteItemsBaseRowSchema>;

export const RouteItemsInsertSchema = z.object({
	group_id: z.uuid(),
	habitat_id: z.uuid().nullable(),
	id: z.uuid(),
	rank_string: z.string(),
	route_id: z.uuid(),
});

export type RouteItemsInsert = z.infer<typeof RouteItemsInsertSchema>;

export const RouteItemsUpdateSchema = RouteItemsInsertSchema.omit({ id: true }).partial();

export type RouteItemsUpdate = z.infer<typeof RouteItemsUpdateSchema>;
