/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as DesignTokensRouteImport } from './routes/design-tokens'
import { Route as IndexRouteImport } from './routes/index'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignTokensRoute = DesignTokensRouteImport.update({
  id: '/design-tokens',
  path: '/design-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/icons': typeof IconsRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/sandbox': typeof SandboxRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/icons': typeof IconsRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/sandbox': typeof SandboxRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/icons': typeof IconsRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/sandbox': typeof SandboxRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-tokens'
    | '/icons'
    | '/kitchen-sink'
    | '/sandbox'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-tokens'
    | '/icons'
    | '/kitchen-sink'
    | '/sandbox'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/design-tokens'
    | '/icons'
    | '/kitchen-sink'
    | '/sandbox'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignTokensRoute: typeof DesignTokensRoute
  IconsRoute: typeof IconsRoute
  KitchenSinkRoute: typeof KitchenSinkRoute
  SandboxRoute: typeof SandboxRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-tokens': {
      id: '/design-tokens'
      path: '/design-tokens'
      fullPath: '/design-tokens'
      preLoaderRoute: typeof DesignTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignTokensRoute: DesignTokensRoute,
  IconsRoute: IconsRoute,
  KitchenSinkRoute: KitchenSinkRoute,
  SandboxRoute: SandboxRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
